// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	commonpb "github.com/milvus-io/milvus-proto/go-api/v2/commonpb"
	clientv3 "go.etcd.io/etcd/client/v3"

	internalpb "github.com/milvus-io/milvus/internal/proto/internalpb"

	milvuspb "github.com/milvus-io/milvus-proto/go-api/v2/milvuspb"

	mock "github.com/stretchr/testify/mock"

	querypb "github.com/milvus-io/milvus/internal/proto/querypb"

	txnkv "github.com/tikv/client-go/v2/txnkv"
)

// QueryNodeComponent is an autogenerated mock type for the QueryNodeComponent type
type QueryNodeComponent struct {
	mock.Mock
}

type QueryNodeComponent_Expecter struct {
	mock *mock.Mock
}

func (_m *QueryNodeComponent) EXPECT() *QueryNodeComponent_Expecter {
	return &QueryNodeComponent_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *QueryNodeComponent) Delete(_a0 context.Context, _a1 *querypb.DeleteRequest) (*commonpb.Status, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *commonpb.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.DeleteRequest) (*commonpb.Status, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.DeleteRequest) *commonpb.Status); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonpb.Status)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querypb.DeleteRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type QueryNodeComponent_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *querypb.DeleteRequest
func (_e *QueryNodeComponent_Expecter) Delete(_a0 interface{}, _a1 interface{}) *QueryNodeComponent_Delete_Call {
	return &QueryNodeComponent_Delete_Call{Call: _e.mock.On("Delete", _a0, _a1)}
}

func (_c *QueryNodeComponent_Delete_Call) Run(run func(_a0 context.Context, _a1 *querypb.DeleteRequest)) *QueryNodeComponent_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querypb.DeleteRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_Delete_Call) Return(_a0 *commonpb.Status, _a1 error) *QueryNodeComponent_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_Delete_Call) RunAndReturn(run func(context.Context, *querypb.DeleteRequest) (*commonpb.Status, error)) *QueryNodeComponent_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAddress provides a mock function with given fields:
func (_m *QueryNodeComponent) GetAddress() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// QueryNodeComponent_GetAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAddress'
type QueryNodeComponent_GetAddress_Call struct {
	*mock.Call
}

// GetAddress is a helper method to define mock.On call
func (_e *QueryNodeComponent_Expecter) GetAddress() *QueryNodeComponent_GetAddress_Call {
	return &QueryNodeComponent_GetAddress_Call{Call: _e.mock.On("GetAddress")}
}

func (_c *QueryNodeComponent_GetAddress_Call) Run(run func()) *QueryNodeComponent_GetAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueryNodeComponent_GetAddress_Call) Return(_a0 string) *QueryNodeComponent_GetAddress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryNodeComponent_GetAddress_Call) RunAndReturn(run func() string) *QueryNodeComponent_GetAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponentStates provides a mock function with given fields: ctx
func (_m *QueryNodeComponent) GetComponentStates(ctx context.Context) (*milvuspb.ComponentStates, error) {
	ret := _m.Called(ctx)

	var r0 *milvuspb.ComponentStates
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*milvuspb.ComponentStates, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *milvuspb.ComponentStates); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*milvuspb.ComponentStates)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_GetComponentStates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponentStates'
type QueryNodeComponent_GetComponentStates_Call struct {
	*mock.Call
}

// GetComponentStates is a helper method to define mock.On call
//   - ctx context.Context
func (_e *QueryNodeComponent_Expecter) GetComponentStates(ctx interface{}) *QueryNodeComponent_GetComponentStates_Call {
	return &QueryNodeComponent_GetComponentStates_Call{Call: _e.mock.On("GetComponentStates", ctx)}
}

func (_c *QueryNodeComponent_GetComponentStates_Call) Run(run func(ctx context.Context)) *QueryNodeComponent_GetComponentStates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *QueryNodeComponent_GetComponentStates_Call) Return(_a0 *milvuspb.ComponentStates, _a1 error) *QueryNodeComponent_GetComponentStates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_GetComponentStates_Call) RunAndReturn(run func(context.Context) (*milvuspb.ComponentStates, error)) *QueryNodeComponent_GetComponentStates_Call {
	_c.Call.Return(run)
	return _c
}

// GetDataDistribution provides a mock function with given fields: _a0, _a1
func (_m *QueryNodeComponent) GetDataDistribution(_a0 context.Context, _a1 *querypb.GetDataDistributionRequest) (*querypb.GetDataDistributionResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *querypb.GetDataDistributionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.GetDataDistributionRequest) (*querypb.GetDataDistributionResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.GetDataDistributionRequest) *querypb.GetDataDistributionResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*querypb.GetDataDistributionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querypb.GetDataDistributionRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_GetDataDistribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDataDistribution'
type QueryNodeComponent_GetDataDistribution_Call struct {
	*mock.Call
}

// GetDataDistribution is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *querypb.GetDataDistributionRequest
func (_e *QueryNodeComponent_Expecter) GetDataDistribution(_a0 interface{}, _a1 interface{}) *QueryNodeComponent_GetDataDistribution_Call {
	return &QueryNodeComponent_GetDataDistribution_Call{Call: _e.mock.On("GetDataDistribution", _a0, _a1)}
}

func (_c *QueryNodeComponent_GetDataDistribution_Call) Run(run func(_a0 context.Context, _a1 *querypb.GetDataDistributionRequest)) *QueryNodeComponent_GetDataDistribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querypb.GetDataDistributionRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_GetDataDistribution_Call) Return(_a0 *querypb.GetDataDistributionResponse, _a1 error) *QueryNodeComponent_GetDataDistribution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_GetDataDistribution_Call) RunAndReturn(run func(context.Context, *querypb.GetDataDistributionRequest) (*querypb.GetDataDistributionResponse, error)) *QueryNodeComponent_GetDataDistribution_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetrics provides a mock function with given fields: ctx, req
func (_m *QueryNodeComponent) GetMetrics(ctx context.Context, req *milvuspb.GetMetricsRequest) (*milvuspb.GetMetricsResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *milvuspb.GetMetricsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *milvuspb.GetMetricsRequest) (*milvuspb.GetMetricsResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *milvuspb.GetMetricsRequest) *milvuspb.GetMetricsResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*milvuspb.GetMetricsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *milvuspb.GetMetricsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_GetMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetrics'
type QueryNodeComponent_GetMetrics_Call struct {
	*mock.Call
}

// GetMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - req *milvuspb.GetMetricsRequest
func (_e *QueryNodeComponent_Expecter) GetMetrics(ctx interface{}, req interface{}) *QueryNodeComponent_GetMetrics_Call {
	return &QueryNodeComponent_GetMetrics_Call{Call: _e.mock.On("GetMetrics", ctx, req)}
}

func (_c *QueryNodeComponent_GetMetrics_Call) Run(run func(ctx context.Context, req *milvuspb.GetMetricsRequest)) *QueryNodeComponent_GetMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*milvuspb.GetMetricsRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_GetMetrics_Call) Return(_a0 *milvuspb.GetMetricsResponse, _a1 error) *QueryNodeComponent_GetMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_GetMetrics_Call) RunAndReturn(run func(context.Context, *milvuspb.GetMetricsRequest) (*milvuspb.GetMetricsResponse, error)) *QueryNodeComponent_GetMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetSegmentInfo provides a mock function with given fields: ctx, req
func (_m *QueryNodeComponent) GetSegmentInfo(ctx context.Context, req *querypb.GetSegmentInfoRequest) (*querypb.GetSegmentInfoResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *querypb.GetSegmentInfoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.GetSegmentInfoRequest) (*querypb.GetSegmentInfoResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.GetSegmentInfoRequest) *querypb.GetSegmentInfoResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*querypb.GetSegmentInfoResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querypb.GetSegmentInfoRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_GetSegmentInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSegmentInfo'
type QueryNodeComponent_GetSegmentInfo_Call struct {
	*mock.Call
}

// GetSegmentInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - req *querypb.GetSegmentInfoRequest
func (_e *QueryNodeComponent_Expecter) GetSegmentInfo(ctx interface{}, req interface{}) *QueryNodeComponent_GetSegmentInfo_Call {
	return &QueryNodeComponent_GetSegmentInfo_Call{Call: _e.mock.On("GetSegmentInfo", ctx, req)}
}

func (_c *QueryNodeComponent_GetSegmentInfo_Call) Run(run func(ctx context.Context, req *querypb.GetSegmentInfoRequest)) *QueryNodeComponent_GetSegmentInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querypb.GetSegmentInfoRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_GetSegmentInfo_Call) Return(_a0 *querypb.GetSegmentInfoResponse, _a1 error) *QueryNodeComponent_GetSegmentInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_GetSegmentInfo_Call) RunAndReturn(run func(context.Context, *querypb.GetSegmentInfoRequest) (*querypb.GetSegmentInfoResponse, error)) *QueryNodeComponent_GetSegmentInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatistics provides a mock function with given fields: ctx, req
func (_m *QueryNodeComponent) GetStatistics(ctx context.Context, req *querypb.GetStatisticsRequest) (*internalpb.GetStatisticsResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *internalpb.GetStatisticsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.GetStatisticsRequest) (*internalpb.GetStatisticsResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.GetStatisticsRequest) *internalpb.GetStatisticsResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalpb.GetStatisticsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querypb.GetStatisticsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_GetStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatistics'
type QueryNodeComponent_GetStatistics_Call struct {
	*mock.Call
}

// GetStatistics is a helper method to define mock.On call
//   - ctx context.Context
//   - req *querypb.GetStatisticsRequest
func (_e *QueryNodeComponent_Expecter) GetStatistics(ctx interface{}, req interface{}) *QueryNodeComponent_GetStatistics_Call {
	return &QueryNodeComponent_GetStatistics_Call{Call: _e.mock.On("GetStatistics", ctx, req)}
}

func (_c *QueryNodeComponent_GetStatistics_Call) Run(run func(ctx context.Context, req *querypb.GetStatisticsRequest)) *QueryNodeComponent_GetStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querypb.GetStatisticsRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_GetStatistics_Call) Return(_a0 *internalpb.GetStatisticsResponse, _a1 error) *QueryNodeComponent_GetStatistics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_GetStatistics_Call) RunAndReturn(run func(context.Context, *querypb.GetStatisticsRequest) (*internalpb.GetStatisticsResponse, error)) *QueryNodeComponent_GetStatistics_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatisticsChannel provides a mock function with given fields: ctx
func (_m *QueryNodeComponent) GetStatisticsChannel(ctx context.Context) (*milvuspb.StringResponse, error) {
	ret := _m.Called(ctx)

	var r0 *milvuspb.StringResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*milvuspb.StringResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *milvuspb.StringResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*milvuspb.StringResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_GetStatisticsChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatisticsChannel'
type QueryNodeComponent_GetStatisticsChannel_Call struct {
	*mock.Call
}

// GetStatisticsChannel is a helper method to define mock.On call
//   - ctx context.Context
func (_e *QueryNodeComponent_Expecter) GetStatisticsChannel(ctx interface{}) *QueryNodeComponent_GetStatisticsChannel_Call {
	return &QueryNodeComponent_GetStatisticsChannel_Call{Call: _e.mock.On("GetStatisticsChannel", ctx)}
}

func (_c *QueryNodeComponent_GetStatisticsChannel_Call) Run(run func(ctx context.Context)) *QueryNodeComponent_GetStatisticsChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *QueryNodeComponent_GetStatisticsChannel_Call) Return(_a0 *milvuspb.StringResponse, _a1 error) *QueryNodeComponent_GetStatisticsChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_GetStatisticsChannel_Call) RunAndReturn(run func(context.Context) (*milvuspb.StringResponse, error)) *QueryNodeComponent_GetStatisticsChannel_Call {
	_c.Call.Return(run)
	return _c
}

// GetTimeTickChannel provides a mock function with given fields: ctx
func (_m *QueryNodeComponent) GetTimeTickChannel(ctx context.Context) (*milvuspb.StringResponse, error) {
	ret := _m.Called(ctx)

	var r0 *milvuspb.StringResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*milvuspb.StringResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *milvuspb.StringResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*milvuspb.StringResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_GetTimeTickChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimeTickChannel'
type QueryNodeComponent_GetTimeTickChannel_Call struct {
	*mock.Call
}

// GetTimeTickChannel is a helper method to define mock.On call
//   - ctx context.Context
func (_e *QueryNodeComponent_Expecter) GetTimeTickChannel(ctx interface{}) *QueryNodeComponent_GetTimeTickChannel_Call {
	return &QueryNodeComponent_GetTimeTickChannel_Call{Call: _e.mock.On("GetTimeTickChannel", ctx)}
}

func (_c *QueryNodeComponent_GetTimeTickChannel_Call) Run(run func(ctx context.Context)) *QueryNodeComponent_GetTimeTickChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *QueryNodeComponent_GetTimeTickChannel_Call) Return(_a0 *milvuspb.StringResponse, _a1 error) *QueryNodeComponent_GetTimeTickChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_GetTimeTickChannel_Call) RunAndReturn(run func(context.Context) (*milvuspb.StringResponse, error)) *QueryNodeComponent_GetTimeTickChannel_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function with given fields:
func (_m *QueryNodeComponent) Init() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueryNodeComponent_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type QueryNodeComponent_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
func (_e *QueryNodeComponent_Expecter) Init() *QueryNodeComponent_Init_Call {
	return &QueryNodeComponent_Init_Call{Call: _e.mock.On("Init")}
}

func (_c *QueryNodeComponent_Init_Call) Run(run func()) *QueryNodeComponent_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueryNodeComponent_Init_Call) Return(_a0 error) *QueryNodeComponent_Init_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryNodeComponent_Init_Call) RunAndReturn(run func() error) *QueryNodeComponent_Init_Call {
	_c.Call.Return(run)
	return _c
}

// LoadPartitions provides a mock function with given fields: ctx, req
func (_m *QueryNodeComponent) LoadPartitions(ctx context.Context, req *querypb.LoadPartitionsRequest) (*commonpb.Status, error) {
	ret := _m.Called(ctx, req)

	var r0 *commonpb.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.LoadPartitionsRequest) (*commonpb.Status, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.LoadPartitionsRequest) *commonpb.Status); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonpb.Status)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querypb.LoadPartitionsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_LoadPartitions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadPartitions'
type QueryNodeComponent_LoadPartitions_Call struct {
	*mock.Call
}

// LoadPartitions is a helper method to define mock.On call
//   - ctx context.Context
//   - req *querypb.LoadPartitionsRequest
func (_e *QueryNodeComponent_Expecter) LoadPartitions(ctx interface{}, req interface{}) *QueryNodeComponent_LoadPartitions_Call {
	return &QueryNodeComponent_LoadPartitions_Call{Call: _e.mock.On("LoadPartitions", ctx, req)}
}

func (_c *QueryNodeComponent_LoadPartitions_Call) Run(run func(ctx context.Context, req *querypb.LoadPartitionsRequest)) *QueryNodeComponent_LoadPartitions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querypb.LoadPartitionsRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_LoadPartitions_Call) Return(_a0 *commonpb.Status, _a1 error) *QueryNodeComponent_LoadPartitions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_LoadPartitions_Call) RunAndReturn(run func(context.Context, *querypb.LoadPartitionsRequest) (*commonpb.Status, error)) *QueryNodeComponent_LoadPartitions_Call {
	_c.Call.Return(run)
	return _c
}

// LoadSegments provides a mock function with given fields: ctx, req
func (_m *QueryNodeComponent) LoadSegments(ctx context.Context, req *querypb.LoadSegmentsRequest) (*commonpb.Status, error) {
	ret := _m.Called(ctx, req)

	var r0 *commonpb.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.LoadSegmentsRequest) (*commonpb.Status, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.LoadSegmentsRequest) *commonpb.Status); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonpb.Status)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querypb.LoadSegmentsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_LoadSegments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadSegments'
type QueryNodeComponent_LoadSegments_Call struct {
	*mock.Call
}

// LoadSegments is a helper method to define mock.On call
//   - ctx context.Context
//   - req *querypb.LoadSegmentsRequest
func (_e *QueryNodeComponent_Expecter) LoadSegments(ctx interface{}, req interface{}) *QueryNodeComponent_LoadSegments_Call {
	return &QueryNodeComponent_LoadSegments_Call{Call: _e.mock.On("LoadSegments", ctx, req)}
}

func (_c *QueryNodeComponent_LoadSegments_Call) Run(run func(ctx context.Context, req *querypb.LoadSegmentsRequest)) *QueryNodeComponent_LoadSegments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querypb.LoadSegmentsRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_LoadSegments_Call) Return(_a0 *commonpb.Status, _a1 error) *QueryNodeComponent_LoadSegments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_LoadSegments_Call) RunAndReturn(run func(context.Context, *querypb.LoadSegmentsRequest) (*commonpb.Status, error)) *QueryNodeComponent_LoadSegments_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, req
func (_m *QueryNodeComponent) Query(ctx context.Context, req *querypb.QueryRequest) (*internalpb.RetrieveResults, error) {
	ret := _m.Called(ctx, req)

	var r0 *internalpb.RetrieveResults
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.QueryRequest) (*internalpb.RetrieveResults, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.QueryRequest) *internalpb.RetrieveResults); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalpb.RetrieveResults)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querypb.QueryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type QueryNodeComponent_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - req *querypb.QueryRequest
func (_e *QueryNodeComponent_Expecter) Query(ctx interface{}, req interface{}) *QueryNodeComponent_Query_Call {
	return &QueryNodeComponent_Query_Call{Call: _e.mock.On("Query", ctx, req)}
}

func (_c *QueryNodeComponent_Query_Call) Run(run func(ctx context.Context, req *querypb.QueryRequest)) *QueryNodeComponent_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querypb.QueryRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_Query_Call) Return(_a0 *internalpb.RetrieveResults, _a1 error) *QueryNodeComponent_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_Query_Call) RunAndReturn(run func(context.Context, *querypb.QueryRequest) (*internalpb.RetrieveResults, error)) *QueryNodeComponent_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QuerySegments provides a mock function with given fields: ctx, req
func (_m *QueryNodeComponent) QuerySegments(ctx context.Context, req *querypb.QueryRequest) (*internalpb.RetrieveResults, error) {
	ret := _m.Called(ctx, req)

	var r0 *internalpb.RetrieveResults
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.QueryRequest) (*internalpb.RetrieveResults, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.QueryRequest) *internalpb.RetrieveResults); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalpb.RetrieveResults)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querypb.QueryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_QuerySegments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QuerySegments'
type QueryNodeComponent_QuerySegments_Call struct {
	*mock.Call
}

// QuerySegments is a helper method to define mock.On call
//   - ctx context.Context
//   - req *querypb.QueryRequest
func (_e *QueryNodeComponent_Expecter) QuerySegments(ctx interface{}, req interface{}) *QueryNodeComponent_QuerySegments_Call {
	return &QueryNodeComponent_QuerySegments_Call{Call: _e.mock.On("QuerySegments", ctx, req)}
}

func (_c *QueryNodeComponent_QuerySegments_Call) Run(run func(ctx context.Context, req *querypb.QueryRequest)) *QueryNodeComponent_QuerySegments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querypb.QueryRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_QuerySegments_Call) Return(_a0 *internalpb.RetrieveResults, _a1 error) *QueryNodeComponent_QuerySegments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_QuerySegments_Call) RunAndReturn(run func(context.Context, *querypb.QueryRequest) (*internalpb.RetrieveResults, error)) *QueryNodeComponent_QuerySegments_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields:
func (_m *QueryNodeComponent) Register() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueryNodeComponent_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type QueryNodeComponent_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
func (_e *QueryNodeComponent_Expecter) Register() *QueryNodeComponent_Register_Call {
	return &QueryNodeComponent_Register_Call{Call: _e.mock.On("Register")}
}

func (_c *QueryNodeComponent_Register_Call) Run(run func()) *QueryNodeComponent_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueryNodeComponent_Register_Call) Return(_a0 error) *QueryNodeComponent_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryNodeComponent_Register_Call) RunAndReturn(run func() error) *QueryNodeComponent_Register_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseCollection provides a mock function with given fields: ctx, req
func (_m *QueryNodeComponent) ReleaseCollection(ctx context.Context, req *querypb.ReleaseCollectionRequest) (*commonpb.Status, error) {
	ret := _m.Called(ctx, req)

	var r0 *commonpb.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.ReleaseCollectionRequest) (*commonpb.Status, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.ReleaseCollectionRequest) *commonpb.Status); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonpb.Status)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querypb.ReleaseCollectionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_ReleaseCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseCollection'
type QueryNodeComponent_ReleaseCollection_Call struct {
	*mock.Call
}

// ReleaseCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - req *querypb.ReleaseCollectionRequest
func (_e *QueryNodeComponent_Expecter) ReleaseCollection(ctx interface{}, req interface{}) *QueryNodeComponent_ReleaseCollection_Call {
	return &QueryNodeComponent_ReleaseCollection_Call{Call: _e.mock.On("ReleaseCollection", ctx, req)}
}

func (_c *QueryNodeComponent_ReleaseCollection_Call) Run(run func(ctx context.Context, req *querypb.ReleaseCollectionRequest)) *QueryNodeComponent_ReleaseCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querypb.ReleaseCollectionRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_ReleaseCollection_Call) Return(_a0 *commonpb.Status, _a1 error) *QueryNodeComponent_ReleaseCollection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_ReleaseCollection_Call) RunAndReturn(run func(context.Context, *querypb.ReleaseCollectionRequest) (*commonpb.Status, error)) *QueryNodeComponent_ReleaseCollection_Call {
	_c.Call.Return(run)
	return _c
}

// ReleasePartitions provides a mock function with given fields: ctx, req
func (_m *QueryNodeComponent) ReleasePartitions(ctx context.Context, req *querypb.ReleasePartitionsRequest) (*commonpb.Status, error) {
	ret := _m.Called(ctx, req)

	var r0 *commonpb.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.ReleasePartitionsRequest) (*commonpb.Status, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.ReleasePartitionsRequest) *commonpb.Status); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonpb.Status)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querypb.ReleasePartitionsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_ReleasePartitions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleasePartitions'
type QueryNodeComponent_ReleasePartitions_Call struct {
	*mock.Call
}

// ReleasePartitions is a helper method to define mock.On call
//   - ctx context.Context
//   - req *querypb.ReleasePartitionsRequest
func (_e *QueryNodeComponent_Expecter) ReleasePartitions(ctx interface{}, req interface{}) *QueryNodeComponent_ReleasePartitions_Call {
	return &QueryNodeComponent_ReleasePartitions_Call{Call: _e.mock.On("ReleasePartitions", ctx, req)}
}

func (_c *QueryNodeComponent_ReleasePartitions_Call) Run(run func(ctx context.Context, req *querypb.ReleasePartitionsRequest)) *QueryNodeComponent_ReleasePartitions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querypb.ReleasePartitionsRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_ReleasePartitions_Call) Return(_a0 *commonpb.Status, _a1 error) *QueryNodeComponent_ReleasePartitions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_ReleasePartitions_Call) RunAndReturn(run func(context.Context, *querypb.ReleasePartitionsRequest) (*commonpb.Status, error)) *QueryNodeComponent_ReleasePartitions_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseSegments provides a mock function with given fields: ctx, req
func (_m *QueryNodeComponent) ReleaseSegments(ctx context.Context, req *querypb.ReleaseSegmentsRequest) (*commonpb.Status, error) {
	ret := _m.Called(ctx, req)

	var r0 *commonpb.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.ReleaseSegmentsRequest) (*commonpb.Status, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.ReleaseSegmentsRequest) *commonpb.Status); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonpb.Status)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querypb.ReleaseSegmentsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_ReleaseSegments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseSegments'
type QueryNodeComponent_ReleaseSegments_Call struct {
	*mock.Call
}

// ReleaseSegments is a helper method to define mock.On call
//   - ctx context.Context
//   - req *querypb.ReleaseSegmentsRequest
func (_e *QueryNodeComponent_Expecter) ReleaseSegments(ctx interface{}, req interface{}) *QueryNodeComponent_ReleaseSegments_Call {
	return &QueryNodeComponent_ReleaseSegments_Call{Call: _e.mock.On("ReleaseSegments", ctx, req)}
}

func (_c *QueryNodeComponent_ReleaseSegments_Call) Run(run func(ctx context.Context, req *querypb.ReleaseSegmentsRequest)) *QueryNodeComponent_ReleaseSegments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querypb.ReleaseSegmentsRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_ReleaseSegments_Call) Return(_a0 *commonpb.Status, _a1 error) *QueryNodeComponent_ReleaseSegments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_ReleaseSegments_Call) RunAndReturn(run func(context.Context, *querypb.ReleaseSegmentsRequest) (*commonpb.Status, error)) *QueryNodeComponent_ReleaseSegments_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, req
func (_m *QueryNodeComponent) Search(ctx context.Context, req *querypb.SearchRequest) (*internalpb.SearchResults, error) {
	ret := _m.Called(ctx, req)

	var r0 *internalpb.SearchResults
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.SearchRequest) (*internalpb.SearchResults, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.SearchRequest) *internalpb.SearchResults); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalpb.SearchResults)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querypb.SearchRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type QueryNodeComponent_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - req *querypb.SearchRequest
func (_e *QueryNodeComponent_Expecter) Search(ctx interface{}, req interface{}) *QueryNodeComponent_Search_Call {
	return &QueryNodeComponent_Search_Call{Call: _e.mock.On("Search", ctx, req)}
}

func (_c *QueryNodeComponent_Search_Call) Run(run func(ctx context.Context, req *querypb.SearchRequest)) *QueryNodeComponent_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querypb.SearchRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_Search_Call) Return(_a0 *internalpb.SearchResults, _a1 error) *QueryNodeComponent_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_Search_Call) RunAndReturn(run func(context.Context, *querypb.SearchRequest) (*internalpb.SearchResults, error)) *QueryNodeComponent_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SearchSegments provides a mock function with given fields: ctx, req
func (_m *QueryNodeComponent) SearchSegments(ctx context.Context, req *querypb.SearchRequest) (*internalpb.SearchResults, error) {
	ret := _m.Called(ctx, req)

	var r0 *internalpb.SearchResults
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.SearchRequest) (*internalpb.SearchResults, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.SearchRequest) *internalpb.SearchResults); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalpb.SearchResults)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querypb.SearchRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_SearchSegments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchSegments'
type QueryNodeComponent_SearchSegments_Call struct {
	*mock.Call
}

// SearchSegments is a helper method to define mock.On call
//   - ctx context.Context
//   - req *querypb.SearchRequest
func (_e *QueryNodeComponent_Expecter) SearchSegments(ctx interface{}, req interface{}) *QueryNodeComponent_SearchSegments_Call {
	return &QueryNodeComponent_SearchSegments_Call{Call: _e.mock.On("SearchSegments", ctx, req)}
}

func (_c *QueryNodeComponent_SearchSegments_Call) Run(run func(ctx context.Context, req *querypb.SearchRequest)) *QueryNodeComponent_SearchSegments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querypb.SearchRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_SearchSegments_Call) Return(_a0 *internalpb.SearchResults, _a1 error) *QueryNodeComponent_SearchSegments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_SearchSegments_Call) RunAndReturn(run func(context.Context, *querypb.SearchRequest) (*internalpb.SearchResults, error)) *QueryNodeComponent_SearchSegments_Call {
	_c.Call.Return(run)
	return _c
}

// SetAddress provides a mock function with given fields: address
func (_m *QueryNodeComponent) SetAddress(address string) {
	_m.Called(address)
}

// QueryNodeComponent_SetAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAddress'
type QueryNodeComponent_SetAddress_Call struct {
	*mock.Call
}

// SetAddress is a helper method to define mock.On call
//   - address string
func (_e *QueryNodeComponent_Expecter) SetAddress(address interface{}) *QueryNodeComponent_SetAddress_Call {
	return &QueryNodeComponent_SetAddress_Call{Call: _e.mock.On("SetAddress", address)}
}

func (_c *QueryNodeComponent_SetAddress_Call) Run(run func(address string)) *QueryNodeComponent_SetAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *QueryNodeComponent_SetAddress_Call) Return() *QueryNodeComponent_SetAddress_Call {
	_c.Call.Return()
	return _c
}

func (_c *QueryNodeComponent_SetAddress_Call) RunAndReturn(run func(string)) *QueryNodeComponent_SetAddress_Call {
	_c.Call.Return(run)
	return _c
}

// SetEtcdClient provides a mock function with given fields: etcdClient
func (_m *QueryNodeComponent) SetEtcdClient(etcdClient *clientv3.Client) {
	_m.Called(etcdClient)
}

// QueryNodeComponent_SetEtcdClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEtcdClient'
type QueryNodeComponent_SetEtcdClient_Call struct {
	*mock.Call
}

// SetEtcdClient is a helper method to define mock.On call
//   - etcdClient *clientv3.Client
func (_e *QueryNodeComponent_Expecter) SetEtcdClient(etcdClient interface{}) *QueryNodeComponent_SetEtcdClient_Call {
	return &QueryNodeComponent_SetEtcdClient_Call{Call: _e.mock.On("SetEtcdClient", etcdClient)}
}

func (_c *QueryNodeComponent_SetEtcdClient_Call) Run(run func(etcdClient *clientv3.Client)) *QueryNodeComponent_SetEtcdClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*clientv3.Client))
	})
	return _c
}

func (_c *QueryNodeComponent_SetEtcdClient_Call) Return() *QueryNodeComponent_SetEtcdClient_Call {
	_c.Call.Return()
	return _c
}

func (_c *QueryNodeComponent_SetEtcdClient_Call) RunAndReturn(run func(*clientv3.Client)) *QueryNodeComponent_SetEtcdClient_Call {
	_c.Call.Return(run)
	return _c
}

// SetTiKVClient provides a mock function with given fields: client
func (_m *QueryNodeComponent) SetTiKVClient(client *txnkv.Client) {
	_m.Called(client)
}

// QueryNodeComponent_SetTiKVClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTiKVClient'
type QueryNodeComponent_SetTiKVClient_Call struct {
	*mock.Call
}

// SetTiKVClient is a helper method to define mock.On call
//   - client *txnkv.Client
func (_e *QueryNodeComponent_Expecter) SetTiKVClient(client interface{}) *QueryNodeComponent_SetTiKVClient_Call {
	return &QueryNodeComponent_SetTiKVClient_Call{Call: _e.mock.On("SetTiKVClient", client)}
}

func (_c *QueryNodeComponent_SetTiKVClient_Call) Run(run func(client *txnkv.Client)) *QueryNodeComponent_SetTiKVClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*txnkv.Client))
	})
	return _c
}

func (_c *QueryNodeComponent_SetTiKVClient_Call) Return() *QueryNodeComponent_SetTiKVClient_Call {
	_c.Call.Return()
	return _c
}

func (_c *QueryNodeComponent_SetTiKVClient_Call) RunAndReturn(run func(*txnkv.Client)) *QueryNodeComponent_SetTiKVClient_Call {
	_c.Call.Return(run)
	return _c
}

// ShowConfigurations provides a mock function with given fields: ctx, req
func (_m *QueryNodeComponent) ShowConfigurations(ctx context.Context, req *internalpb.ShowConfigurationsRequest) (*internalpb.ShowConfigurationsResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *internalpb.ShowConfigurationsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *internalpb.ShowConfigurationsRequest) (*internalpb.ShowConfigurationsResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *internalpb.ShowConfigurationsRequest) *internalpb.ShowConfigurationsResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalpb.ShowConfigurationsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *internalpb.ShowConfigurationsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_ShowConfigurations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowConfigurations'
type QueryNodeComponent_ShowConfigurations_Call struct {
	*mock.Call
}

// ShowConfigurations is a helper method to define mock.On call
//   - ctx context.Context
//   - req *internalpb.ShowConfigurationsRequest
func (_e *QueryNodeComponent_Expecter) ShowConfigurations(ctx interface{}, req interface{}) *QueryNodeComponent_ShowConfigurations_Call {
	return &QueryNodeComponent_ShowConfigurations_Call{Call: _e.mock.On("ShowConfigurations", ctx, req)}
}

func (_c *QueryNodeComponent_ShowConfigurations_Call) Run(run func(ctx context.Context, req *internalpb.ShowConfigurationsRequest)) *QueryNodeComponent_ShowConfigurations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*internalpb.ShowConfigurationsRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_ShowConfigurations_Call) Return(_a0 *internalpb.ShowConfigurationsResponse, _a1 error) *QueryNodeComponent_ShowConfigurations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_ShowConfigurations_Call) RunAndReturn(run func(context.Context, *internalpb.ShowConfigurationsRequest) (*internalpb.ShowConfigurationsResponse, error)) *QueryNodeComponent_ShowConfigurations_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields:
func (_m *QueryNodeComponent) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueryNodeComponent_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type QueryNodeComponent_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *QueryNodeComponent_Expecter) Start() *QueryNodeComponent_Start_Call {
	return &QueryNodeComponent_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *QueryNodeComponent_Start_Call) Run(run func()) *QueryNodeComponent_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueryNodeComponent_Start_Call) Return(_a0 error) *QueryNodeComponent_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryNodeComponent_Start_Call) RunAndReturn(run func() error) *QueryNodeComponent_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields:
func (_m *QueryNodeComponent) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueryNodeComponent_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type QueryNodeComponent_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *QueryNodeComponent_Expecter) Stop() *QueryNodeComponent_Stop_Call {
	return &QueryNodeComponent_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *QueryNodeComponent_Stop_Call) Run(run func()) *QueryNodeComponent_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueryNodeComponent_Stop_Call) Return(_a0 error) *QueryNodeComponent_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryNodeComponent_Stop_Call) RunAndReturn(run func() error) *QueryNodeComponent_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// SyncDistribution provides a mock function with given fields: _a0, _a1
func (_m *QueryNodeComponent) SyncDistribution(_a0 context.Context, _a1 *querypb.SyncDistributionRequest) (*commonpb.Status, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *commonpb.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.SyncDistributionRequest) (*commonpb.Status, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.SyncDistributionRequest) *commonpb.Status); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonpb.Status)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querypb.SyncDistributionRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_SyncDistribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncDistribution'
type QueryNodeComponent_SyncDistribution_Call struct {
	*mock.Call
}

// SyncDistribution is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *querypb.SyncDistributionRequest
func (_e *QueryNodeComponent_Expecter) SyncDistribution(_a0 interface{}, _a1 interface{}) *QueryNodeComponent_SyncDistribution_Call {
	return &QueryNodeComponent_SyncDistribution_Call{Call: _e.mock.On("SyncDistribution", _a0, _a1)}
}

func (_c *QueryNodeComponent_SyncDistribution_Call) Run(run func(_a0 context.Context, _a1 *querypb.SyncDistributionRequest)) *QueryNodeComponent_SyncDistribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querypb.SyncDistributionRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_SyncDistribution_Call) Return(_a0 *commonpb.Status, _a1 error) *QueryNodeComponent_SyncDistribution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_SyncDistribution_Call) RunAndReturn(run func(context.Context, *querypb.SyncDistributionRequest) (*commonpb.Status, error)) *QueryNodeComponent_SyncDistribution_Call {
	_c.Call.Return(run)
	return _c
}

// SyncReplicaSegments provides a mock function with given fields: ctx, req
func (_m *QueryNodeComponent) SyncReplicaSegments(ctx context.Context, req *querypb.SyncReplicaSegmentsRequest) (*commonpb.Status, error) {
	ret := _m.Called(ctx, req)

	var r0 *commonpb.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.SyncReplicaSegmentsRequest) (*commonpb.Status, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.SyncReplicaSegmentsRequest) *commonpb.Status); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonpb.Status)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querypb.SyncReplicaSegmentsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_SyncReplicaSegments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncReplicaSegments'
type QueryNodeComponent_SyncReplicaSegments_Call struct {
	*mock.Call
}

// SyncReplicaSegments is a helper method to define mock.On call
//   - ctx context.Context
//   - req *querypb.SyncReplicaSegmentsRequest
func (_e *QueryNodeComponent_Expecter) SyncReplicaSegments(ctx interface{}, req interface{}) *QueryNodeComponent_SyncReplicaSegments_Call {
	return &QueryNodeComponent_SyncReplicaSegments_Call{Call: _e.mock.On("SyncReplicaSegments", ctx, req)}
}

func (_c *QueryNodeComponent_SyncReplicaSegments_Call) Run(run func(ctx context.Context, req *querypb.SyncReplicaSegmentsRequest)) *QueryNodeComponent_SyncReplicaSegments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querypb.SyncReplicaSegmentsRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_SyncReplicaSegments_Call) Return(_a0 *commonpb.Status, _a1 error) *QueryNodeComponent_SyncReplicaSegments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_SyncReplicaSegments_Call) RunAndReturn(run func(context.Context, *querypb.SyncReplicaSegmentsRequest) (*commonpb.Status, error)) *QueryNodeComponent_SyncReplicaSegments_Call {
	_c.Call.Return(run)
	return _c
}

// UnsubDmChannel provides a mock function with given fields: ctx, req
func (_m *QueryNodeComponent) UnsubDmChannel(ctx context.Context, req *querypb.UnsubDmChannelRequest) (*commonpb.Status, error) {
	ret := _m.Called(ctx, req)

	var r0 *commonpb.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.UnsubDmChannelRequest) (*commonpb.Status, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.UnsubDmChannelRequest) *commonpb.Status); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonpb.Status)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querypb.UnsubDmChannelRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_UnsubDmChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsubDmChannel'
type QueryNodeComponent_UnsubDmChannel_Call struct {
	*mock.Call
}

// UnsubDmChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - req *querypb.UnsubDmChannelRequest
func (_e *QueryNodeComponent_Expecter) UnsubDmChannel(ctx interface{}, req interface{}) *QueryNodeComponent_UnsubDmChannel_Call {
	return &QueryNodeComponent_UnsubDmChannel_Call{Call: _e.mock.On("UnsubDmChannel", ctx, req)}
}

func (_c *QueryNodeComponent_UnsubDmChannel_Call) Run(run func(ctx context.Context, req *querypb.UnsubDmChannelRequest)) *QueryNodeComponent_UnsubDmChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querypb.UnsubDmChannelRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_UnsubDmChannel_Call) Return(_a0 *commonpb.Status, _a1 error) *QueryNodeComponent_UnsubDmChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_UnsubDmChannel_Call) RunAndReturn(run func(context.Context, *querypb.UnsubDmChannelRequest) (*commonpb.Status, error)) *QueryNodeComponent_UnsubDmChannel_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStateCode provides a mock function with given fields: stateCode
func (_m *QueryNodeComponent) UpdateStateCode(stateCode commonpb.StateCode) {
	_m.Called(stateCode)
}

// QueryNodeComponent_UpdateStateCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStateCode'
type QueryNodeComponent_UpdateStateCode_Call struct {
	*mock.Call
}

// UpdateStateCode is a helper method to define mock.On call
//   - stateCode commonpb.StateCode
func (_e *QueryNodeComponent_Expecter) UpdateStateCode(stateCode interface{}) *QueryNodeComponent_UpdateStateCode_Call {
	return &QueryNodeComponent_UpdateStateCode_Call{Call: _e.mock.On("UpdateStateCode", stateCode)}
}

func (_c *QueryNodeComponent_UpdateStateCode_Call) Run(run func(stateCode commonpb.StateCode)) *QueryNodeComponent_UpdateStateCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(commonpb.StateCode))
	})
	return _c
}

func (_c *QueryNodeComponent_UpdateStateCode_Call) Return() *QueryNodeComponent_UpdateStateCode_Call {
	_c.Call.Return()
	return _c
}

func (_c *QueryNodeComponent_UpdateStateCode_Call) RunAndReturn(run func(commonpb.StateCode)) *QueryNodeComponent_UpdateStateCode_Call {
	_c.Call.Return(run)
	return _c
}

// WatchDmChannels provides a mock function with given fields: ctx, req
func (_m *QueryNodeComponent) WatchDmChannels(ctx context.Context, req *querypb.WatchDmChannelsRequest) (*commonpb.Status, error) {
	ret := _m.Called(ctx, req)

	var r0 *commonpb.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.WatchDmChannelsRequest) (*commonpb.Status, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querypb.WatchDmChannelsRequest) *commonpb.Status); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonpb.Status)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querypb.WatchDmChannelsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryNodeComponent_WatchDmChannels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchDmChannels'
type QueryNodeComponent_WatchDmChannels_Call struct {
	*mock.Call
}

// WatchDmChannels is a helper method to define mock.On call
//   - ctx context.Context
//   - req *querypb.WatchDmChannelsRequest
func (_e *QueryNodeComponent_Expecter) WatchDmChannels(ctx interface{}, req interface{}) *QueryNodeComponent_WatchDmChannels_Call {
	return &QueryNodeComponent_WatchDmChannels_Call{Call: _e.mock.On("WatchDmChannels", ctx, req)}
}

func (_c *QueryNodeComponent_WatchDmChannels_Call) Run(run func(ctx context.Context, req *querypb.WatchDmChannelsRequest)) *QueryNodeComponent_WatchDmChannels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querypb.WatchDmChannelsRequest))
	})
	return _c
}

func (_c *QueryNodeComponent_WatchDmChannels_Call) Return(_a0 *commonpb.Status, _a1 error) *QueryNodeComponent_WatchDmChannels_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryNodeComponent_WatchDmChannels_Call) RunAndReturn(run func(context.Context, *querypb.WatchDmChannelsRequest) (*commonpb.Status, error)) *QueryNodeComponent_WatchDmChannels_Call {
	_c.Call.Return(run)
	return _c
}

// NewQueryNodeComponent creates a new instance of QueryNodeComponent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryNodeComponent(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryNodeComponent {
	mock := &QueryNodeComponent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
