name: 'Milvus Cache'
description: ''
runs:
  using: "composite"
  steps:
  - name: 'Generate CCache Hash'
    run: |
      CORE_HASH=""
      if [ -d "internal/core" ]; then
        # Find all matching files and calculate hash (macOS compatible)
        FILES=$(find internal/core -type f \( -name "*.cpp" -o -name "*.cc" -o -name "*.c" -o -name "*.h" -o -name "*.hpp" -o -name "CMakeLists.txt" \) 2>/dev/null | sort)
        if [ -n "$FILES" ]; then
          CORE_HASH=$(echo "$FILES" | xargs cat 2>/dev/null | shasum -a 256 | cut -d' ' -f1)
        fi
      fi
      echo "corehash=${CORE_HASH}" >> $GITHUB_ENV
      echo "Set CCache hash to ${CORE_HASH:-empty}"
    shell: bash
  - name: Mac Cache CCache Volumes
    uses: actions/cache/restore@v4
    with:
      path: /var/tmp/ccache
      key: macos15-ccache-${{ env.corehash }}
      restore-keys: macos15-ccache-
  - name: Mac Cache Go Mod Volumes
    id: go-mod-cache
    run: |
      GO_MOD_HASH=""
      if find . -name "go.sum" -type f | grep -q .; then
        GO_MOD_HASH=$(find . -name "go.sum" -type f -exec cat {} \; 2>/dev/null | shasum -a 256 | cut -d' ' -f1)
      fi
      echo "hash=${GO_MOD_HASH}" >> $GITHUB_OUTPUT
    shell: bash
  - name: Restore Go Mod Cache
    uses: actions/cache/restore@v4
    with:
      path: ~/go/pkg/mod
      key: macos15-go-mod-${{ steps.go-mod-cache.outputs.hash }}
      restore-keys: macos15-go-mod-
  - name: Mac Cache Conan Packages
    id: conan-cache
    run: |
      CONAN_HASH=""
      if find internal/core -name "conanfile.*" -type f 2>/dev/null | grep -q .; then
        CONAN_HASH=$(find internal/core -name "conanfile.*" -type f -exec cat {} \; 2>/dev/null | shasum -a 256 | cut -d' ' -f1)
      fi
      echo "hash=${CONAN_HASH}" >> $GITHUB_OUTPUT
    shell: bash
  - name: Restore Conan Cache
    uses: actions/cache/restore@v4
    with:
      path: ~/.conan
      key: macos15-conan-${{ steps.conan-cache.outputs.hash }}
      restore-keys: macos15-conan-
