// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dbmodel "github.com/milvus-io/milvus/internal/metastore/db/dbmodel"
	mock "github.com/stretchr/testify/mock"
)

// IMetaDomain is an autogenerated mock type for the IMetaDomain type
type IMetaDomain struct {
	mock.Mock
}

// CollAliasDb provides a mock function with given fields: ctx
func (_m *IMetaDomain) CollAliasDb(ctx context.Context) dbmodel.ICollAliasDb {
	ret := _m.Called(ctx)

	var r0 dbmodel.ICollAliasDb
	if rf, ok := ret.Get(0).(func(context.Context) dbmodel.ICollAliasDb); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dbmodel.ICollAliasDb)
		}
	}

	return r0
}

// CollChannelDb provides a mock function with given fields: ctx
func (_m *IMetaDomain) CollChannelDb(ctx context.Context) dbmodel.ICollChannelDb {
	ret := _m.Called(ctx)

	var r0 dbmodel.ICollChannelDb
	if rf, ok := ret.Get(0).(func(context.Context) dbmodel.ICollChannelDb); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dbmodel.ICollChannelDb)
		}
	}

	return r0
}

// CollectionDb provides a mock function with given fields: ctx
func (_m *IMetaDomain) CollectionDb(ctx context.Context) dbmodel.ICollectionDb {
	ret := _m.Called(ctx)

	var r0 dbmodel.ICollectionDb
	if rf, ok := ret.Get(0).(func(context.Context) dbmodel.ICollectionDb); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dbmodel.ICollectionDb)
		}
	}

	return r0
}

// FieldDb provides a mock function with given fields: ctx
func (_m *IMetaDomain) FieldDb(ctx context.Context) dbmodel.IFieldDb {
	ret := _m.Called(ctx)

	var r0 dbmodel.IFieldDb
	if rf, ok := ret.Get(0).(func(context.Context) dbmodel.IFieldDb); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dbmodel.IFieldDb)
		}
	}

	return r0
}

// IndexDb provides a mock function with given fields: ctx
func (_m *IMetaDomain) IndexDb(ctx context.Context) dbmodel.IIndexDb {
	ret := _m.Called(ctx)

	var r0 dbmodel.IIndexDb
	if rf, ok := ret.Get(0).(func(context.Context) dbmodel.IIndexDb); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dbmodel.IIndexDb)
		}
	}

	return r0
}

// PartitionDb provides a mock function with given fields: ctx
func (_m *IMetaDomain) PartitionDb(ctx context.Context) dbmodel.IPartitionDb {
	ret := _m.Called(ctx)

	var r0 dbmodel.IPartitionDb
	if rf, ok := ret.Get(0).(func(context.Context) dbmodel.IPartitionDb); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dbmodel.IPartitionDb)
		}
	}

	return r0
}

// SegmentIndexDb provides a mock function with given fields: ctx
func (_m *IMetaDomain) SegmentIndexDb(ctx context.Context) dbmodel.ISegmentIndexDb {
	ret := _m.Called(ctx)

	var r0 dbmodel.ISegmentIndexDb
	if rf, ok := ret.Get(0).(func(context.Context) dbmodel.ISegmentIndexDb); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dbmodel.ISegmentIndexDb)
		}
	}

	return r0
}

// UserDb provides a mock function with given fields: ctx
func (_m *IMetaDomain) UserDb(ctx context.Context) dbmodel.IUserDb {
	ret := _m.Called(ctx)

	var r0 dbmodel.IUserDb
	if rf, ok := ret.Get(0).(func(context.Context) dbmodel.IUserDb); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dbmodel.IUserDb)
		}
	}

	return r0
}

type mockConstructorTestingTNewIMetaDomain interface {
	mock.TestingT
	Cleanup(func())
}

// NewIMetaDomain creates a new instance of IMetaDomain. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIMetaDomain(t mockConstructorTestingTNewIMetaDomain) *IMetaDomain {
	mock := &IMetaDomain{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
