// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal.proto

package internalpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	commonpb "github.com/milvus-io/milvus/internal/proto/commonpb"
	schemapb "github.com/milvus-io/milvus/internal/proto/schemapb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StateCode int32

const (
	StateCode_Initializing StateCode = 0
	StateCode_Healthy      StateCode = 1
	StateCode_Abnormal     StateCode = 2
)

var StateCode_name = map[int32]string{
	0: "Initializing",
	1: "Healthy",
	2: "Abnormal",
}

var StateCode_value = map[string]int32{
	"Initializing": 0,
	"Healthy":      1,
	"Abnormal":     2,
}

func (x StateCode) String() string {
	return proto.EnumName(StateCode_name, int32(x))
}

func (StateCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{0}
}

type InsertDataVersion int32

const (
	// 0 must refer to row-based format, since it's the first version in Milvus.
	InsertDataVersion_RowBased    InsertDataVersion = 0
	InsertDataVersion_ColumnBased InsertDataVersion = 1
)

var InsertDataVersion_name = map[int32]string{
	0: "RowBased",
	1: "ColumnBased",
}

var InsertDataVersion_value = map[string]int32{
	"RowBased":    0,
	"ColumnBased": 1,
}

func (x InsertDataVersion) String() string {
	return proto.EnumName(InsertDataVersion_name, int32(x))
}

func (InsertDataVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{1}
}

type ComponentInfo struct {
	NodeID               int64                    `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Role                 string                   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	StateCode            StateCode                `protobuf:"varint,3,opt,name=state_code,json=stateCode,proto3,enum=milvus.proto.internal.StateCode" json:"state_code,omitempty"`
	ExtraInfo            []*commonpb.KeyValuePair `protobuf:"bytes,4,rep,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ComponentInfo) Reset()         { *m = ComponentInfo{} }
func (m *ComponentInfo) String() string { return proto.CompactTextString(m) }
func (*ComponentInfo) ProtoMessage()    {}
func (*ComponentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{0}
}

func (m *ComponentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentInfo.Unmarshal(m, b)
}
func (m *ComponentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentInfo.Marshal(b, m, deterministic)
}
func (m *ComponentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentInfo.Merge(m, src)
}
func (m *ComponentInfo) XXX_Size() int {
	return xxx_messageInfo_ComponentInfo.Size(m)
}
func (m *ComponentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentInfo proto.InternalMessageInfo

func (m *ComponentInfo) GetNodeID() int64 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *ComponentInfo) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *ComponentInfo) GetStateCode() StateCode {
	if m != nil {
		return m.StateCode
	}
	return StateCode_Initializing
}

func (m *ComponentInfo) GetExtraInfo() []*commonpb.KeyValuePair {
	if m != nil {
		return m.ExtraInfo
	}
	return nil
}

type ComponentStates struct {
	State                *ComponentInfo   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	SubcomponentStates   []*ComponentInfo `protobuf:"bytes,2,rep,name=subcomponent_states,json=subcomponentStates,proto3" json:"subcomponent_states,omitempty"`
	Status               *commonpb.Status `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ComponentStates) Reset()         { *m = ComponentStates{} }
func (m *ComponentStates) String() string { return proto.CompactTextString(m) }
func (*ComponentStates) ProtoMessage()    {}
func (*ComponentStates) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{1}
}

func (m *ComponentStates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentStates.Unmarshal(m, b)
}
func (m *ComponentStates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentStates.Marshal(b, m, deterministic)
}
func (m *ComponentStates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentStates.Merge(m, src)
}
func (m *ComponentStates) XXX_Size() int {
	return xxx_messageInfo_ComponentStates.Size(m)
}
func (m *ComponentStates) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentStates.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentStates proto.InternalMessageInfo

func (m *ComponentStates) GetState() *ComponentInfo {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *ComponentStates) GetSubcomponentStates() []*ComponentInfo {
	if m != nil {
		return m.SubcomponentStates
	}
	return nil
}

func (m *ComponentStates) GetStatus() *commonpb.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetComponentStatesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetComponentStatesRequest) Reset()         { *m = GetComponentStatesRequest{} }
func (m *GetComponentStatesRequest) String() string { return proto.CompactTextString(m) }
func (*GetComponentStatesRequest) ProtoMessage()    {}
func (*GetComponentStatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{2}
}

func (m *GetComponentStatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetComponentStatesRequest.Unmarshal(m, b)
}
func (m *GetComponentStatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetComponentStatesRequest.Marshal(b, m, deterministic)
}
func (m *GetComponentStatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetComponentStatesRequest.Merge(m, src)
}
func (m *GetComponentStatesRequest) XXX_Size() int {
	return xxx_messageInfo_GetComponentStatesRequest.Size(m)
}
func (m *GetComponentStatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetComponentStatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetComponentStatesRequest proto.InternalMessageInfo

type GetTimeTickChannelRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTimeTickChannelRequest) Reset()         { *m = GetTimeTickChannelRequest{} }
func (m *GetTimeTickChannelRequest) String() string { return proto.CompactTextString(m) }
func (*GetTimeTickChannelRequest) ProtoMessage()    {}
func (*GetTimeTickChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{3}
}

func (m *GetTimeTickChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTimeTickChannelRequest.Unmarshal(m, b)
}
func (m *GetTimeTickChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTimeTickChannelRequest.Marshal(b, m, deterministic)
}
func (m *GetTimeTickChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTimeTickChannelRequest.Merge(m, src)
}
func (m *GetTimeTickChannelRequest) XXX_Size() int {
	return xxx_messageInfo_GetTimeTickChannelRequest.Size(m)
}
func (m *GetTimeTickChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTimeTickChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTimeTickChannelRequest proto.InternalMessageInfo

type GetStatisticsChannelRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatisticsChannelRequest) Reset()         { *m = GetStatisticsChannelRequest{} }
func (m *GetStatisticsChannelRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatisticsChannelRequest) ProtoMessage()    {}
func (*GetStatisticsChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{4}
}

func (m *GetStatisticsChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatisticsChannelRequest.Unmarshal(m, b)
}
func (m *GetStatisticsChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatisticsChannelRequest.Marshal(b, m, deterministic)
}
func (m *GetStatisticsChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatisticsChannelRequest.Merge(m, src)
}
func (m *GetStatisticsChannelRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatisticsChannelRequest.Size(m)
}
func (m *GetStatisticsChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatisticsChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatisticsChannelRequest proto.InternalMessageInfo

type GetDdChannelRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDdChannelRequest) Reset()         { *m = GetDdChannelRequest{} }
func (m *GetDdChannelRequest) String() string { return proto.CompactTextString(m) }
func (*GetDdChannelRequest) ProtoMessage()    {}
func (*GetDdChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{5}
}

func (m *GetDdChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDdChannelRequest.Unmarshal(m, b)
}
func (m *GetDdChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDdChannelRequest.Marshal(b, m, deterministic)
}
func (m *GetDdChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDdChannelRequest.Merge(m, src)
}
func (m *GetDdChannelRequest) XXX_Size() int {
	return xxx_messageInfo_GetDdChannelRequest.Size(m)
}
func (m *GetDdChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDdChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDdChannelRequest proto.InternalMessageInfo

type NodeInfo struct {
	Address              *commonpb.Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Role                 string            `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{6}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetAddress() *commonpb.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *NodeInfo) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type InitParams struct {
	NodeID               int64                    `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	StartParams          []*commonpb.KeyValuePair `protobuf:"bytes,2,rep,name=start_params,json=startParams,proto3" json:"start_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *InitParams) Reset()         { *m = InitParams{} }
func (m *InitParams) String() string { return proto.CompactTextString(m) }
func (*InitParams) ProtoMessage()    {}
func (*InitParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{7}
}

func (m *InitParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitParams.Unmarshal(m, b)
}
func (m *InitParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitParams.Marshal(b, m, deterministic)
}
func (m *InitParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitParams.Merge(m, src)
}
func (m *InitParams) XXX_Size() int {
	return xxx_messageInfo_InitParams.Size(m)
}
func (m *InitParams) XXX_DiscardUnknown() {
	xxx_messageInfo_InitParams.DiscardUnknown(m)
}

var xxx_messageInfo_InitParams proto.InternalMessageInfo

func (m *InitParams) GetNodeID() int64 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *InitParams) GetStartParams() []*commonpb.KeyValuePair {
	if m != nil {
		return m.StartParams
	}
	return nil
}

type StringList struct {
	Values               []string         `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	Status               *commonpb.Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StringList) Reset()         { *m = StringList{} }
func (m *StringList) String() string { return proto.CompactTextString(m) }
func (*StringList) ProtoMessage()    {}
func (*StringList) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{8}
}

func (m *StringList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringList.Unmarshal(m, b)
}
func (m *StringList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringList.Marshal(b, m, deterministic)
}
func (m *StringList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringList.Merge(m, src)
}
func (m *StringList) XXX_Size() int {
	return xxx_messageInfo_StringList.Size(m)
}
func (m *StringList) XXX_DiscardUnknown() {
	xxx_messageInfo_StringList.DiscardUnknown(m)
}

var xxx_messageInfo_StringList proto.InternalMessageInfo

func (m *StringList) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *StringList) GetStatus() *commonpb.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type TimeTickMsg struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TimeTickMsg) Reset()         { *m = TimeTickMsg{} }
func (m *TimeTickMsg) String() string { return proto.CompactTextString(m) }
func (*TimeTickMsg) ProtoMessage()    {}
func (*TimeTickMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{9}
}

func (m *TimeTickMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeTickMsg.Unmarshal(m, b)
}
func (m *TimeTickMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeTickMsg.Marshal(b, m, deterministic)
}
func (m *TimeTickMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeTickMsg.Merge(m, src)
}
func (m *TimeTickMsg) XXX_Size() int {
	return xxx_messageInfo_TimeTickMsg.Size(m)
}
func (m *TimeTickMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeTickMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TimeTickMsg proto.InternalMessageInfo

func (m *TimeTickMsg) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

type CreateCollectionRequest struct {
	Base           *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName         string            `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName string            `protobuf:"bytes,3,opt,name=collectionName,proto3" json:"collectionName,omitempty"`
	PartitionName  string            `protobuf:"bytes,4,opt,name=partitionName,proto3" json:"partitionName,omitempty"`
	// `schema` is the serialized `schema.CollectionSchema`
	DbID                 int64    `protobuf:"varint,5,opt,name=dbID,proto3" json:"dbID,omitempty"`
	CollectionID         int64    `protobuf:"varint,6,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	PartitionID          int64    `protobuf:"varint,7,opt,name=partitionID,proto3" json:"partitionID,omitempty"`
	Schema               []byte   `protobuf:"bytes,8,opt,name=schema,proto3" json:"schema,omitempty"`
	VirtualChannelNames  []string `protobuf:"bytes,9,rep,name=virtualChannelNames,proto3" json:"virtualChannelNames,omitempty"`
	PhysicalChannelNames []string `protobuf:"bytes,10,rep,name=physicalChannelNames,proto3" json:"physicalChannelNames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCollectionRequest) Reset()         { *m = CreateCollectionRequest{} }
func (m *CreateCollectionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCollectionRequest) ProtoMessage()    {}
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{10}
}

func (m *CreateCollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCollectionRequest.Unmarshal(m, b)
}
func (m *CreateCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCollectionRequest.Marshal(b, m, deterministic)
}
func (m *CreateCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCollectionRequest.Merge(m, src)
}
func (m *CreateCollectionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCollectionRequest.Size(m)
}
func (m *CreateCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCollectionRequest proto.InternalMessageInfo

func (m *CreateCollectionRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *CreateCollectionRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *CreateCollectionRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *CreateCollectionRequest) GetPartitionName() string {
	if m != nil {
		return m.PartitionName
	}
	return ""
}

func (m *CreateCollectionRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *CreateCollectionRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *CreateCollectionRequest) GetPartitionID() int64 {
	if m != nil {
		return m.PartitionID
	}
	return 0
}

func (m *CreateCollectionRequest) GetSchema() []byte {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *CreateCollectionRequest) GetVirtualChannelNames() []string {
	if m != nil {
		return m.VirtualChannelNames
	}
	return nil
}

func (m *CreateCollectionRequest) GetPhysicalChannelNames() []string {
	if m != nil {
		return m.PhysicalChannelNames
	}
	return nil
}

type DropCollectionRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string            `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName       string            `protobuf:"bytes,3,opt,name=collectionName,proto3" json:"collectionName,omitempty"`
	DbID                 int64             `protobuf:"varint,4,opt,name=dbID,proto3" json:"dbID,omitempty"`
	CollectionID         int64             `protobuf:"varint,5,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DropCollectionRequest) Reset()         { *m = DropCollectionRequest{} }
func (m *DropCollectionRequest) String() string { return proto.CompactTextString(m) }
func (*DropCollectionRequest) ProtoMessage()    {}
func (*DropCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{11}
}

func (m *DropCollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropCollectionRequest.Unmarshal(m, b)
}
func (m *DropCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropCollectionRequest.Marshal(b, m, deterministic)
}
func (m *DropCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropCollectionRequest.Merge(m, src)
}
func (m *DropCollectionRequest) XXX_Size() int {
	return xxx_messageInfo_DropCollectionRequest.Size(m)
}
func (m *DropCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DropCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DropCollectionRequest proto.InternalMessageInfo

func (m *DropCollectionRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DropCollectionRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *DropCollectionRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *DropCollectionRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *DropCollectionRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

type CreatePartitionRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string            `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName       string            `protobuf:"bytes,3,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	PartitionName        string            `protobuf:"bytes,4,opt,name=partition_name,json=partitionName,proto3" json:"partition_name,omitempty"`
	DbID                 int64             `protobuf:"varint,5,opt,name=dbID,proto3" json:"dbID,omitempty"`
	CollectionID         int64             `protobuf:"varint,6,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	PartitionID          int64             `protobuf:"varint,7,opt,name=partitionID,proto3" json:"partitionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreatePartitionRequest) Reset()         { *m = CreatePartitionRequest{} }
func (m *CreatePartitionRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePartitionRequest) ProtoMessage()    {}
func (*CreatePartitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{12}
}

func (m *CreatePartitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePartitionRequest.Unmarshal(m, b)
}
func (m *CreatePartitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePartitionRequest.Marshal(b, m, deterministic)
}
func (m *CreatePartitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePartitionRequest.Merge(m, src)
}
func (m *CreatePartitionRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePartitionRequest.Size(m)
}
func (m *CreatePartitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePartitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePartitionRequest proto.InternalMessageInfo

func (m *CreatePartitionRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *CreatePartitionRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *CreatePartitionRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *CreatePartitionRequest) GetPartitionName() string {
	if m != nil {
		return m.PartitionName
	}
	return ""
}

func (m *CreatePartitionRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *CreatePartitionRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *CreatePartitionRequest) GetPartitionID() int64 {
	if m != nil {
		return m.PartitionID
	}
	return 0
}

type DropPartitionRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string            `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName       string            `protobuf:"bytes,3,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	PartitionName        string            `protobuf:"bytes,4,opt,name=partition_name,json=partitionName,proto3" json:"partition_name,omitempty"`
	DbID                 int64             `protobuf:"varint,5,opt,name=dbID,proto3" json:"dbID,omitempty"`
	CollectionID         int64             `protobuf:"varint,6,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	PartitionID          int64             `protobuf:"varint,7,opt,name=partitionID,proto3" json:"partitionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DropPartitionRequest) Reset()         { *m = DropPartitionRequest{} }
func (m *DropPartitionRequest) String() string { return proto.CompactTextString(m) }
func (*DropPartitionRequest) ProtoMessage()    {}
func (*DropPartitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{13}
}

func (m *DropPartitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropPartitionRequest.Unmarshal(m, b)
}
func (m *DropPartitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropPartitionRequest.Marshal(b, m, deterministic)
}
func (m *DropPartitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropPartitionRequest.Merge(m, src)
}
func (m *DropPartitionRequest) XXX_Size() int {
	return xxx_messageInfo_DropPartitionRequest.Size(m)
}
func (m *DropPartitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DropPartitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DropPartitionRequest proto.InternalMessageInfo

func (m *DropPartitionRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DropPartitionRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *DropPartitionRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *DropPartitionRequest) GetPartitionName() string {
	if m != nil {
		return m.PartitionName
	}
	return ""
}

func (m *DropPartitionRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *DropPartitionRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *DropPartitionRequest) GetPartitionID() int64 {
	if m != nil {
		return m.PartitionID
	}
	return 0
}

type CreateAliasRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string            `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName       string            `protobuf:"bytes,3,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Alias                string            `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateAliasRequest) Reset()         { *m = CreateAliasRequest{} }
func (m *CreateAliasRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAliasRequest) ProtoMessage()    {}
func (*CreateAliasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{14}
}

func (m *CreateAliasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAliasRequest.Unmarshal(m, b)
}
func (m *CreateAliasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAliasRequest.Marshal(b, m, deterministic)
}
func (m *CreateAliasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAliasRequest.Merge(m, src)
}
func (m *CreateAliasRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAliasRequest.Size(m)
}
func (m *CreateAliasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAliasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAliasRequest proto.InternalMessageInfo

func (m *CreateAliasRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *CreateAliasRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *CreateAliasRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *CreateAliasRequest) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type DropAliasRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string            `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	Alias                string            `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DropAliasRequest) Reset()         { *m = DropAliasRequest{} }
func (m *DropAliasRequest) String() string { return proto.CompactTextString(m) }
func (*DropAliasRequest) ProtoMessage()    {}
func (*DropAliasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{15}
}

func (m *DropAliasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropAliasRequest.Unmarshal(m, b)
}
func (m *DropAliasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropAliasRequest.Marshal(b, m, deterministic)
}
func (m *DropAliasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropAliasRequest.Merge(m, src)
}
func (m *DropAliasRequest) XXX_Size() int {
	return xxx_messageInfo_DropAliasRequest.Size(m)
}
func (m *DropAliasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DropAliasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DropAliasRequest proto.InternalMessageInfo

func (m *DropAliasRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DropAliasRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *DropAliasRequest) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type AlterAliasRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string            `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName       string            `protobuf:"bytes,3,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Alias                string            `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AlterAliasRequest) Reset()         { *m = AlterAliasRequest{} }
func (m *AlterAliasRequest) String() string { return proto.CompactTextString(m) }
func (*AlterAliasRequest) ProtoMessage()    {}
func (*AlterAliasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{16}
}

func (m *AlterAliasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlterAliasRequest.Unmarshal(m, b)
}
func (m *AlterAliasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlterAliasRequest.Marshal(b, m, deterministic)
}
func (m *AlterAliasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlterAliasRequest.Merge(m, src)
}
func (m *AlterAliasRequest) XXX_Size() int {
	return xxx_messageInfo_AlterAliasRequest.Size(m)
}
func (m *AlterAliasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AlterAliasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AlterAliasRequest proto.InternalMessageInfo

func (m *AlterAliasRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *AlterAliasRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *AlterAliasRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *AlterAliasRequest) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type CreateIndexRequest struct {
	Base                 *commonpb.MsgBase        `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string                   `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName       string                   `protobuf:"bytes,3,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	FieldName            string                   `protobuf:"bytes,4,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	DbID                 int64                    `protobuf:"varint,5,opt,name=dbID,proto3" json:"dbID,omitempty"`
	CollectionID         int64                    `protobuf:"varint,6,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	FieldID              int64                    `protobuf:"varint,7,opt,name=fieldID,proto3" json:"fieldID,omitempty"`
	ExtraParams          []*commonpb.KeyValuePair `protobuf:"bytes,8,rep,name=extra_params,json=extraParams,proto3" json:"extra_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CreateIndexRequest) Reset()         { *m = CreateIndexRequest{} }
func (m *CreateIndexRequest) String() string { return proto.CompactTextString(m) }
func (*CreateIndexRequest) ProtoMessage()    {}
func (*CreateIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{17}
}

func (m *CreateIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIndexRequest.Unmarshal(m, b)
}
func (m *CreateIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIndexRequest.Marshal(b, m, deterministic)
}
func (m *CreateIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIndexRequest.Merge(m, src)
}
func (m *CreateIndexRequest) XXX_Size() int {
	return xxx_messageInfo_CreateIndexRequest.Size(m)
}
func (m *CreateIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIndexRequest proto.InternalMessageInfo

func (m *CreateIndexRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *CreateIndexRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *CreateIndexRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *CreateIndexRequest) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *CreateIndexRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *CreateIndexRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *CreateIndexRequest) GetFieldID() int64 {
	if m != nil {
		return m.FieldID
	}
	return 0
}

func (m *CreateIndexRequest) GetExtraParams() []*commonpb.KeyValuePair {
	if m != nil {
		return m.ExtraParams
	}
	return nil
}

type InsertRequest struct {
	Base           *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ShardName      string            `protobuf:"bytes,2,opt,name=shardName,proto3" json:"shardName,omitempty"`
	DbName         string            `protobuf:"bytes,3,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName string            `protobuf:"bytes,4,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	PartitionName  string            `protobuf:"bytes,5,opt,name=partition_name,json=partitionName,proto3" json:"partition_name,omitempty"`
	DbID           int64             `protobuf:"varint,6,opt,name=dbID,proto3" json:"dbID,omitempty"`
	CollectionID   int64             `protobuf:"varint,7,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	PartitionID    int64             `protobuf:"varint,8,opt,name=partitionID,proto3" json:"partitionID,omitempty"`
	SegmentID      int64             `protobuf:"varint,9,opt,name=segmentID,proto3" json:"segmentID,omitempty"`
	Timestamps     []uint64          `protobuf:"varint,10,rep,packed,name=timestamps,proto3" json:"timestamps,omitempty"`
	RowIDs         []int64           `protobuf:"varint,11,rep,packed,name=rowIDs,proto3" json:"rowIDs,omitempty"`
	// row_data was reserved for compatibility
	RowData              []*commonpb.Blob      `protobuf:"bytes,12,rep,name=row_data,json=rowData,proto3" json:"row_data,omitempty"`
	FieldsData           []*schemapb.FieldData `protobuf:"bytes,13,rep,name=fields_data,json=fieldsData,proto3" json:"fields_data,omitempty"`
	NumRows              uint64                `protobuf:"varint,14,opt,name=num_rows,json=numRows,proto3" json:"num_rows,omitempty"`
	Version              InsertDataVersion     `protobuf:"varint,15,opt,name=version,proto3,enum=milvus.proto.internal.InsertDataVersion" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *InsertRequest) Reset()         { *m = InsertRequest{} }
func (m *InsertRequest) String() string { return proto.CompactTextString(m) }
func (*InsertRequest) ProtoMessage()    {}
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{18}
}

func (m *InsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertRequest.Unmarshal(m, b)
}
func (m *InsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertRequest.Marshal(b, m, deterministic)
}
func (m *InsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertRequest.Merge(m, src)
}
func (m *InsertRequest) XXX_Size() int {
	return xxx_messageInfo_InsertRequest.Size(m)
}
func (m *InsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertRequest proto.InternalMessageInfo

func (m *InsertRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *InsertRequest) GetShardName() string {
	if m != nil {
		return m.ShardName
	}
	return ""
}

func (m *InsertRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *InsertRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *InsertRequest) GetPartitionName() string {
	if m != nil {
		return m.PartitionName
	}
	return ""
}

func (m *InsertRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *InsertRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *InsertRequest) GetPartitionID() int64 {
	if m != nil {
		return m.PartitionID
	}
	return 0
}

func (m *InsertRequest) GetSegmentID() int64 {
	if m != nil {
		return m.SegmentID
	}
	return 0
}

func (m *InsertRequest) GetTimestamps() []uint64 {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

func (m *InsertRequest) GetRowIDs() []int64 {
	if m != nil {
		return m.RowIDs
	}
	return nil
}

func (m *InsertRequest) GetRowData() []*commonpb.Blob {
	if m != nil {
		return m.RowData
	}
	return nil
}

func (m *InsertRequest) GetFieldsData() []*schemapb.FieldData {
	if m != nil {
		return m.FieldsData
	}
	return nil
}

func (m *InsertRequest) GetNumRows() uint64 {
	if m != nil {
		return m.NumRows
	}
	return 0
}

func (m *InsertRequest) GetVersion() InsertDataVersion {
	if m != nil {
		return m.Version
	}
	return InsertDataVersion_RowBased
}

type SearchRequest struct {
	Base            *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ResultChannelID string            `protobuf:"bytes,2,opt,name=result_channelID,json=resultChannelID,proto3" json:"result_channelID,omitempty"`
	DbID            int64             `protobuf:"varint,3,opt,name=dbID,proto3" json:"dbID,omitempty"`
	CollectionID    int64             `protobuf:"varint,4,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	PartitionIDs    []int64           `protobuf:"varint,5,rep,packed,name=partitionIDs,proto3" json:"partitionIDs,omitempty"`
	Dsl             string            `protobuf:"bytes,6,opt,name=dsl,proto3" json:"dsl,omitempty"`
	// serialized `PlaceholderGroup`
	PlaceholderGroup     []byte           `protobuf:"bytes,7,opt,name=placeholder_group,json=placeholderGroup,proto3" json:"placeholder_group,omitempty"`
	DslType              commonpb.DslType `protobuf:"varint,8,opt,name=dsl_type,json=dslType,proto3,enum=milvus.proto.common.DslType" json:"dsl_type,omitempty"`
	SerializedExprPlan   []byte           `protobuf:"bytes,9,opt,name=serialized_expr_plan,json=serializedExprPlan,proto3" json:"serialized_expr_plan,omitempty"`
	OutputFieldsId       []int64          `protobuf:"varint,10,rep,packed,name=output_fields_id,json=outputFieldsId,proto3" json:"output_fields_id,omitempty"`
	TravelTimestamp      uint64           `protobuf:"varint,11,opt,name=travel_timestamp,json=travelTimestamp,proto3" json:"travel_timestamp,omitempty"`
	GuaranteeTimestamp   uint64           `protobuf:"varint,12,opt,name=guarantee_timestamp,json=guaranteeTimestamp,proto3" json:"guarantee_timestamp,omitempty"`
	TimeoutTimestamp     uint64           `protobuf:"varint,13,opt,name=timeout_timestamp,json=timeoutTimestamp,proto3" json:"timeout_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{19}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *SearchRequest) GetResultChannelID() string {
	if m != nil {
		return m.ResultChannelID
	}
	return ""
}

func (m *SearchRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *SearchRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *SearchRequest) GetPartitionIDs() []int64 {
	if m != nil {
		return m.PartitionIDs
	}
	return nil
}

func (m *SearchRequest) GetDsl() string {
	if m != nil {
		return m.Dsl
	}
	return ""
}

func (m *SearchRequest) GetPlaceholderGroup() []byte {
	if m != nil {
		return m.PlaceholderGroup
	}
	return nil
}

func (m *SearchRequest) GetDslType() commonpb.DslType {
	if m != nil {
		return m.DslType
	}
	return commonpb.DslType_Dsl
}

func (m *SearchRequest) GetSerializedExprPlan() []byte {
	if m != nil {
		return m.SerializedExprPlan
	}
	return nil
}

func (m *SearchRequest) GetOutputFieldsId() []int64 {
	if m != nil {
		return m.OutputFieldsId
	}
	return nil
}

func (m *SearchRequest) GetTravelTimestamp() uint64 {
	if m != nil {
		return m.TravelTimestamp
	}
	return 0
}

func (m *SearchRequest) GetGuaranteeTimestamp() uint64 {
	if m != nil {
		return m.GuaranteeTimestamp
	}
	return 0
}

func (m *SearchRequest) GetTimeoutTimestamp() uint64 {
	if m != nil {
		return m.TimeoutTimestamp
	}
	return 0
}

type SearchResults struct {
	Base                     *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Status                   *commonpb.Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ResultChannelID          string            `protobuf:"bytes,3,opt,name=result_channelID,json=resultChannelID,proto3" json:"result_channelID,omitempty"`
	MetricType               string            `protobuf:"bytes,4,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	NumQueries               int64             `protobuf:"varint,5,opt,name=num_queries,json=numQueries,proto3" json:"num_queries,omitempty"`
	TopK                     int64             `protobuf:"varint,6,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	SealedSegmentIDsSearched []int64           `protobuf:"varint,7,rep,packed,name=sealed_segmentIDs_searched,json=sealedSegmentIDsSearched,proto3" json:"sealed_segmentIDs_searched,omitempty"`
	ChannelIDsSearched       []string          `protobuf:"bytes,8,rep,name=channelIDs_searched,json=channelIDsSearched,proto3" json:"channelIDs_searched,omitempty"`
	GlobalSealedSegmentIDs   []int64           `protobuf:"varint,9,rep,packed,name=global_sealed_segmentIDs,json=globalSealedSegmentIDs,proto3" json:"global_sealed_segmentIDs,omitempty"`
	// schema.SearchResultsData inside
	SlicedBlob           []byte   `protobuf:"bytes,10,opt,name=sliced_blob,json=slicedBlob,proto3" json:"sliced_blob,omitempty"`
	SlicedNumCount       int64    `protobuf:"varint,11,opt,name=sliced_num_count,json=slicedNumCount,proto3" json:"sliced_num_count,omitempty"`
	SlicedOffset         int64    `protobuf:"varint,12,opt,name=sliced_offset,json=slicedOffset,proto3" json:"sliced_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResults) Reset()         { *m = SearchResults{} }
func (m *SearchResults) String() string { return proto.CompactTextString(m) }
func (*SearchResults) ProtoMessage()    {}
func (*SearchResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{20}
}

func (m *SearchResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResults.Unmarshal(m, b)
}
func (m *SearchResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResults.Marshal(b, m, deterministic)
}
func (m *SearchResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResults.Merge(m, src)
}
func (m *SearchResults) XXX_Size() int {
	return xxx_messageInfo_SearchResults.Size(m)
}
func (m *SearchResults) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResults.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResults proto.InternalMessageInfo

func (m *SearchResults) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *SearchResults) GetStatus() *commonpb.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SearchResults) GetResultChannelID() string {
	if m != nil {
		return m.ResultChannelID
	}
	return ""
}

func (m *SearchResults) GetMetricType() string {
	if m != nil {
		return m.MetricType
	}
	return ""
}

func (m *SearchResults) GetNumQueries() int64 {
	if m != nil {
		return m.NumQueries
	}
	return 0
}

func (m *SearchResults) GetTopK() int64 {
	if m != nil {
		return m.TopK
	}
	return 0
}

func (m *SearchResults) GetSealedSegmentIDsSearched() []int64 {
	if m != nil {
		return m.SealedSegmentIDsSearched
	}
	return nil
}

func (m *SearchResults) GetChannelIDsSearched() []string {
	if m != nil {
		return m.ChannelIDsSearched
	}
	return nil
}

func (m *SearchResults) GetGlobalSealedSegmentIDs() []int64 {
	if m != nil {
		return m.GlobalSealedSegmentIDs
	}
	return nil
}

func (m *SearchResults) GetSlicedBlob() []byte {
	if m != nil {
		return m.SlicedBlob
	}
	return nil
}

func (m *SearchResults) GetSlicedNumCount() int64 {
	if m != nil {
		return m.SlicedNumCount
	}
	return 0
}

func (m *SearchResults) GetSlicedOffset() int64 {
	if m != nil {
		return m.SlicedOffset
	}
	return 0
}

type RetrieveRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ResultChannelID      string            `protobuf:"bytes,2,opt,name=result_channelID,json=resultChannelID,proto3" json:"result_channelID,omitempty"`
	DbID                 int64             `protobuf:"varint,3,opt,name=dbID,proto3" json:"dbID,omitempty"`
	CollectionID         int64             `protobuf:"varint,4,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	PartitionIDs         []int64           `protobuf:"varint,5,rep,packed,name=partitionIDs,proto3" json:"partitionIDs,omitempty"`
	SerializedExprPlan   []byte            `protobuf:"bytes,6,opt,name=serialized_expr_plan,json=serializedExprPlan,proto3" json:"serialized_expr_plan,omitempty"`
	OutputFieldsId       []int64           `protobuf:"varint,7,rep,packed,name=output_fields_id,json=outputFieldsId,proto3" json:"output_fields_id,omitempty"`
	TravelTimestamp      uint64            `protobuf:"varint,8,opt,name=travel_timestamp,json=travelTimestamp,proto3" json:"travel_timestamp,omitempty"`
	GuaranteeTimestamp   uint64            `protobuf:"varint,9,opt,name=guarantee_timestamp,json=guaranteeTimestamp,proto3" json:"guarantee_timestamp,omitempty"`
	TimeoutTimestamp     uint64            `protobuf:"varint,10,opt,name=timeout_timestamp,json=timeoutTimestamp,proto3" json:"timeout_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RetrieveRequest) Reset()         { *m = RetrieveRequest{} }
func (m *RetrieveRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveRequest) ProtoMessage()    {}
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{21}
}

func (m *RetrieveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveRequest.Unmarshal(m, b)
}
func (m *RetrieveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveRequest.Merge(m, src)
}
func (m *RetrieveRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveRequest.Size(m)
}
func (m *RetrieveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveRequest proto.InternalMessageInfo

func (m *RetrieveRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RetrieveRequest) GetResultChannelID() string {
	if m != nil {
		return m.ResultChannelID
	}
	return ""
}

func (m *RetrieveRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *RetrieveRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *RetrieveRequest) GetPartitionIDs() []int64 {
	if m != nil {
		return m.PartitionIDs
	}
	return nil
}

func (m *RetrieveRequest) GetSerializedExprPlan() []byte {
	if m != nil {
		return m.SerializedExprPlan
	}
	return nil
}

func (m *RetrieveRequest) GetOutputFieldsId() []int64 {
	if m != nil {
		return m.OutputFieldsId
	}
	return nil
}

func (m *RetrieveRequest) GetTravelTimestamp() uint64 {
	if m != nil {
		return m.TravelTimestamp
	}
	return 0
}

func (m *RetrieveRequest) GetGuaranteeTimestamp() uint64 {
	if m != nil {
		return m.GuaranteeTimestamp
	}
	return 0
}

func (m *RetrieveRequest) GetTimeoutTimestamp() uint64 {
	if m != nil {
		return m.TimeoutTimestamp
	}
	return 0
}

type RetrieveResults struct {
	Base                      *commonpb.MsgBase     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Status                    *commonpb.Status      `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ResultChannelID           string                `protobuf:"bytes,3,opt,name=result_channelID,json=resultChannelID,proto3" json:"result_channelID,omitempty"`
	Ids                       *schemapb.IDs         `protobuf:"bytes,4,opt,name=ids,proto3" json:"ids,omitempty"`
	FieldsData                []*schemapb.FieldData `protobuf:"bytes,5,rep,name=fields_data,json=fieldsData,proto3" json:"fields_data,omitempty"`
	SealedSegmentIDsRetrieved []int64               `protobuf:"varint,6,rep,packed,name=sealed_segmentIDs_retrieved,json=sealedSegmentIDsRetrieved,proto3" json:"sealed_segmentIDs_retrieved,omitempty"`
	ChannelIDsRetrieved       []string              `protobuf:"bytes,7,rep,name=channelIDs_retrieved,json=channelIDsRetrieved,proto3" json:"channelIDs_retrieved,omitempty"`
	GlobalSealedSegmentIDs    []int64               `protobuf:"varint,8,rep,packed,name=global_sealed_segmentIDs,json=globalSealedSegmentIDs,proto3" json:"global_sealed_segmentIDs,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}              `json:"-"`
	XXX_unrecognized          []byte                `json:"-"`
	XXX_sizecache             int32                 `json:"-"`
}

func (m *RetrieveResults) Reset()         { *m = RetrieveResults{} }
func (m *RetrieveResults) String() string { return proto.CompactTextString(m) }
func (*RetrieveResults) ProtoMessage()    {}
func (*RetrieveResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{22}
}

func (m *RetrieveResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveResults.Unmarshal(m, b)
}
func (m *RetrieveResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveResults.Marshal(b, m, deterministic)
}
func (m *RetrieveResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveResults.Merge(m, src)
}
func (m *RetrieveResults) XXX_Size() int {
	return xxx_messageInfo_RetrieveResults.Size(m)
}
func (m *RetrieveResults) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveResults.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveResults proto.InternalMessageInfo

func (m *RetrieveResults) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RetrieveResults) GetStatus() *commonpb.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RetrieveResults) GetResultChannelID() string {
	if m != nil {
		return m.ResultChannelID
	}
	return ""
}

func (m *RetrieveResults) GetIds() *schemapb.IDs {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *RetrieveResults) GetFieldsData() []*schemapb.FieldData {
	if m != nil {
		return m.FieldsData
	}
	return nil
}

func (m *RetrieveResults) GetSealedSegmentIDsRetrieved() []int64 {
	if m != nil {
		return m.SealedSegmentIDsRetrieved
	}
	return nil
}

func (m *RetrieveResults) GetChannelIDsRetrieved() []string {
	if m != nil {
		return m.ChannelIDsRetrieved
	}
	return nil
}

func (m *RetrieveResults) GetGlobalSealedSegmentIDs() []int64 {
	if m != nil {
		return m.GlobalSealedSegmentIDs
	}
	return nil
}

type DeleteRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ShardName            string            `protobuf:"bytes,2,opt,name=shardName,proto3" json:"shardName,omitempty"`
	DbName               string            `protobuf:"bytes,3,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName       string            `protobuf:"bytes,4,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	PartitionName        string            `protobuf:"bytes,5,opt,name=partition_name,json=partitionName,proto3" json:"partition_name,omitempty"`
	DbID                 int64             `protobuf:"varint,6,opt,name=dbID,proto3" json:"dbID,omitempty"`
	CollectionID         int64             `protobuf:"varint,7,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	PartitionID          int64             `protobuf:"varint,8,opt,name=partitionID,proto3" json:"partitionID,omitempty"`
	Int64PrimaryKeys     []int64           `protobuf:"varint,9,rep,packed,name=int64_primary_keys,json=int64PrimaryKeys,proto3" json:"int64_primary_keys,omitempty"`
	Timestamps           []uint64          `protobuf:"varint,10,rep,packed,name=timestamps,proto3" json:"timestamps,omitempty"`
	NumRows              int64             `protobuf:"varint,11,opt,name=num_rows,json=numRows,proto3" json:"num_rows,omitempty"`
	PrimaryKeys          *schemapb.IDs     `protobuf:"bytes,12,opt,name=primary_keys,json=primaryKeys,proto3" json:"primary_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{23}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DeleteRequest) GetShardName() string {
	if m != nil {
		return m.ShardName
	}
	return ""
}

func (m *DeleteRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *DeleteRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *DeleteRequest) GetPartitionName() string {
	if m != nil {
		return m.PartitionName
	}
	return ""
}

func (m *DeleteRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *DeleteRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *DeleteRequest) GetPartitionID() int64 {
	if m != nil {
		return m.PartitionID
	}
	return 0
}

func (m *DeleteRequest) GetInt64PrimaryKeys() []int64 {
	if m != nil {
		return m.Int64PrimaryKeys
	}
	return nil
}

func (m *DeleteRequest) GetTimestamps() []uint64 {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

func (m *DeleteRequest) GetNumRows() int64 {
	if m != nil {
		return m.NumRows
	}
	return 0
}

func (m *DeleteRequest) GetPrimaryKeys() *schemapb.IDs {
	if m != nil {
		return m.PrimaryKeys
	}
	return nil
}

type LoadIndex struct {
	Base                 *commonpb.MsgBase        `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	SegmentID            int64                    `protobuf:"varint,2,opt,name=segmentID,proto3" json:"segmentID,omitempty"`
	FieldName            string                   `protobuf:"bytes,3,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	FieldID              int64                    `protobuf:"varint,4,opt,name=fieldID,proto3" json:"fieldID,omitempty"`
	IndexPaths           []string                 `protobuf:"bytes,5,rep,name=index_paths,json=indexPaths,proto3" json:"index_paths,omitempty"`
	IndexParams          []*commonpb.KeyValuePair `protobuf:"bytes,6,rep,name=index_params,json=indexParams,proto3" json:"index_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *LoadIndex) Reset()         { *m = LoadIndex{} }
func (m *LoadIndex) String() string { return proto.CompactTextString(m) }
func (*LoadIndex) ProtoMessage()    {}
func (*LoadIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{24}
}

func (m *LoadIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadIndex.Unmarshal(m, b)
}
func (m *LoadIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadIndex.Marshal(b, m, deterministic)
}
func (m *LoadIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadIndex.Merge(m, src)
}
func (m *LoadIndex) XXX_Size() int {
	return xxx_messageInfo_LoadIndex.Size(m)
}
func (m *LoadIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadIndex.DiscardUnknown(m)
}

var xxx_messageInfo_LoadIndex proto.InternalMessageInfo

func (m *LoadIndex) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *LoadIndex) GetSegmentID() int64 {
	if m != nil {
		return m.SegmentID
	}
	return 0
}

func (m *LoadIndex) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *LoadIndex) GetFieldID() int64 {
	if m != nil {
		return m.FieldID
	}
	return 0
}

func (m *LoadIndex) GetIndexPaths() []string {
	if m != nil {
		return m.IndexPaths
	}
	return nil
}

func (m *LoadIndex) GetIndexParams() []*commonpb.KeyValuePair {
	if m != nil {
		return m.IndexParams
	}
	return nil
}

type IndexStats struct {
	IndexParams          []*commonpb.KeyValuePair `protobuf:"bytes,1,rep,name=index_params,json=indexParams,proto3" json:"index_params,omitempty"`
	NumRelatedSegments   int64                    `protobuf:"varint,2,opt,name=num_related_segments,json=numRelatedSegments,proto3" json:"num_related_segments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *IndexStats) Reset()         { *m = IndexStats{} }
func (m *IndexStats) String() string { return proto.CompactTextString(m) }
func (*IndexStats) ProtoMessage()    {}
func (*IndexStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{25}
}

func (m *IndexStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexStats.Unmarshal(m, b)
}
func (m *IndexStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexStats.Marshal(b, m, deterministic)
}
func (m *IndexStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexStats.Merge(m, src)
}
func (m *IndexStats) XXX_Size() int {
	return xxx_messageInfo_IndexStats.Size(m)
}
func (m *IndexStats) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexStats.DiscardUnknown(m)
}

var xxx_messageInfo_IndexStats proto.InternalMessageInfo

func (m *IndexStats) GetIndexParams() []*commonpb.KeyValuePair {
	if m != nil {
		return m.IndexParams
	}
	return nil
}

func (m *IndexStats) GetNumRelatedSegments() int64 {
	if m != nil {
		return m.NumRelatedSegments
	}
	return 0
}

type FieldStats struct {
	CollectionID         int64         `protobuf:"varint,1,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	FieldID              int64         `protobuf:"varint,2,opt,name=fieldID,proto3" json:"fieldID,omitempty"`
	IndexStats           []*IndexStats `protobuf:"bytes,3,rep,name=index_stats,json=indexStats,proto3" json:"index_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FieldStats) Reset()         { *m = FieldStats{} }
func (m *FieldStats) String() string { return proto.CompactTextString(m) }
func (*FieldStats) ProtoMessage()    {}
func (*FieldStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{26}
}

func (m *FieldStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldStats.Unmarshal(m, b)
}
func (m *FieldStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldStats.Marshal(b, m, deterministic)
}
func (m *FieldStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldStats.Merge(m, src)
}
func (m *FieldStats) XXX_Size() int {
	return xxx_messageInfo_FieldStats.Size(m)
}
func (m *FieldStats) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldStats.DiscardUnknown(m)
}

var xxx_messageInfo_FieldStats proto.InternalMessageInfo

func (m *FieldStats) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *FieldStats) GetFieldID() int64 {
	if m != nil {
		return m.FieldID
	}
	return 0
}

func (m *FieldStats) GetIndexStats() []*IndexStats {
	if m != nil {
		return m.IndexStats
	}
	return nil
}

type SegmentStats struct {
	SegmentID            int64    `protobuf:"varint,1,opt,name=segmentID,proto3" json:"segmentID,omitempty"`
	MemorySize           int64    `protobuf:"varint,2,opt,name=memory_size,json=memorySize,proto3" json:"memory_size,omitempty"`
	NumRows              int64    `protobuf:"varint,3,opt,name=num_rows,json=numRows,proto3" json:"num_rows,omitempty"`
	RecentlyModified     bool     `protobuf:"varint,4,opt,name=recently_modified,json=recentlyModified,proto3" json:"recently_modified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentStats) Reset()         { *m = SegmentStats{} }
func (m *SegmentStats) String() string { return proto.CompactTextString(m) }
func (*SegmentStats) ProtoMessage()    {}
func (*SegmentStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{27}
}

func (m *SegmentStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentStats.Unmarshal(m, b)
}
func (m *SegmentStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentStats.Marshal(b, m, deterministic)
}
func (m *SegmentStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentStats.Merge(m, src)
}
func (m *SegmentStats) XXX_Size() int {
	return xxx_messageInfo_SegmentStats.Size(m)
}
func (m *SegmentStats) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentStats.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentStats proto.InternalMessageInfo

func (m *SegmentStats) GetSegmentID() int64 {
	if m != nil {
		return m.SegmentID
	}
	return 0
}

func (m *SegmentStats) GetMemorySize() int64 {
	if m != nil {
		return m.MemorySize
	}
	return 0
}

func (m *SegmentStats) GetNumRows() int64 {
	if m != nil {
		return m.NumRows
	}
	return 0
}

func (m *SegmentStats) GetRecentlyModified() bool {
	if m != nil {
		return m.RecentlyModified
	}
	return false
}

type QueryNodeStats struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	SegStats             []*SegmentStats   `protobuf:"bytes,2,rep,name=seg_stats,json=segStats,proto3" json:"seg_stats,omitempty"`
	FieldStats           []*FieldStats     `protobuf:"bytes,3,rep,name=field_stats,json=fieldStats,proto3" json:"field_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueryNodeStats) Reset()         { *m = QueryNodeStats{} }
func (m *QueryNodeStats) String() string { return proto.CompactTextString(m) }
func (*QueryNodeStats) ProtoMessage()    {}
func (*QueryNodeStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{28}
}

func (m *QueryNodeStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryNodeStats.Unmarshal(m, b)
}
func (m *QueryNodeStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryNodeStats.Marshal(b, m, deterministic)
}
func (m *QueryNodeStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNodeStats.Merge(m, src)
}
func (m *QueryNodeStats) XXX_Size() int {
	return xxx_messageInfo_QueryNodeStats.Size(m)
}
func (m *QueryNodeStats) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNodeStats.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNodeStats proto.InternalMessageInfo

func (m *QueryNodeStats) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *QueryNodeStats) GetSegStats() []*SegmentStats {
	if m != nil {
		return m.SegStats
	}
	return nil
}

func (m *QueryNodeStats) GetFieldStats() []*FieldStats {
	if m != nil {
		return m.FieldStats
	}
	return nil
}

type MsgPosition struct {
	ChannelName          string   `protobuf:"bytes,1,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	MsgID                []byte   `protobuf:"bytes,2,opt,name=msgID,proto3" json:"msgID,omitempty"`
	MsgGroup             string   `protobuf:"bytes,3,opt,name=msgGroup,proto3" json:"msgGroup,omitempty"`
	Timestamp            uint64   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgPosition) Reset()         { *m = MsgPosition{} }
func (m *MsgPosition) String() string { return proto.CompactTextString(m) }
func (*MsgPosition) ProtoMessage()    {}
func (*MsgPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{29}
}

func (m *MsgPosition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgPosition.Unmarshal(m, b)
}
func (m *MsgPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgPosition.Marshal(b, m, deterministic)
}
func (m *MsgPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPosition.Merge(m, src)
}
func (m *MsgPosition) XXX_Size() int {
	return xxx_messageInfo_MsgPosition.Size(m)
}
func (m *MsgPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPosition.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPosition proto.InternalMessageInfo

func (m *MsgPosition) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *MsgPosition) GetMsgID() []byte {
	if m != nil {
		return m.MsgID
	}
	return nil
}

func (m *MsgPosition) GetMsgGroup() string {
	if m != nil {
		return m.MsgGroup
	}
	return ""
}

func (m *MsgPosition) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ChannelTimeTickMsg struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ChannelNames         []string          `protobuf:"bytes,2,rep,name=channelNames,proto3" json:"channelNames,omitempty"`
	Timestamps           []uint64          `protobuf:"varint,3,rep,packed,name=timestamps,proto3" json:"timestamps,omitempty"`
	DefaultTimestamp     uint64            `protobuf:"varint,4,opt,name=default_timestamp,json=defaultTimestamp,proto3" json:"default_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ChannelTimeTickMsg) Reset()         { *m = ChannelTimeTickMsg{} }
func (m *ChannelTimeTickMsg) String() string { return proto.CompactTextString(m) }
func (*ChannelTimeTickMsg) ProtoMessage()    {}
func (*ChannelTimeTickMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{30}
}

func (m *ChannelTimeTickMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelTimeTickMsg.Unmarshal(m, b)
}
func (m *ChannelTimeTickMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelTimeTickMsg.Marshal(b, m, deterministic)
}
func (m *ChannelTimeTickMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelTimeTickMsg.Merge(m, src)
}
func (m *ChannelTimeTickMsg) XXX_Size() int {
	return xxx_messageInfo_ChannelTimeTickMsg.Size(m)
}
func (m *ChannelTimeTickMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelTimeTickMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelTimeTickMsg proto.InternalMessageInfo

func (m *ChannelTimeTickMsg) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ChannelTimeTickMsg) GetChannelNames() []string {
	if m != nil {
		return m.ChannelNames
	}
	return nil
}

func (m *ChannelTimeTickMsg) GetTimestamps() []uint64 {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

func (m *ChannelTimeTickMsg) GetDefaultTimestamp() uint64 {
	if m != nil {
		return m.DefaultTimestamp
	}
	return 0
}

type ClearCredUsersCacheRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearCredUsersCacheRequest) Reset()         { *m = ClearCredUsersCacheRequest{} }
func (m *ClearCredUsersCacheRequest) String() string { return proto.CompactTextString(m) }
func (*ClearCredUsersCacheRequest) ProtoMessage()    {}
func (*ClearCredUsersCacheRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{31}
}

func (m *ClearCredUsersCacheRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearCredUsersCacheRequest.Unmarshal(m, b)
}
func (m *ClearCredUsersCacheRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearCredUsersCacheRequest.Marshal(b, m, deterministic)
}
func (m *ClearCredUsersCacheRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearCredUsersCacheRequest.Merge(m, src)
}
func (m *ClearCredUsersCacheRequest) XXX_Size() int {
	return xxx_messageInfo_ClearCredUsersCacheRequest.Size(m)
}
func (m *ClearCredUsersCacheRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearCredUsersCacheRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearCredUsersCacheRequest proto.InternalMessageInfo

type CredentialInfo struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	EncryptedPassword    string   `protobuf:"bytes,2,opt,name=encrypted_password,json=encryptedPassword,proto3" json:"encrypted_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CredentialInfo) Reset()         { *m = CredentialInfo{} }
func (m *CredentialInfo) String() string { return proto.CompactTextString(m) }
func (*CredentialInfo) ProtoMessage()    {}
func (*CredentialInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{32}
}

func (m *CredentialInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialInfo.Unmarshal(m, b)
}
func (m *CredentialInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialInfo.Marshal(b, m, deterministic)
}
func (m *CredentialInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialInfo.Merge(m, src)
}
func (m *CredentialInfo) XXX_Size() int {
	return xxx_messageInfo_CredentialInfo.Size(m)
}
func (m *CredentialInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialInfo proto.InternalMessageInfo

func (m *CredentialInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CredentialInfo) GetEncryptedPassword() string {
	if m != nil {
		return m.EncryptedPassword
	}
	return ""
}

func init() {
	proto.RegisterEnum("milvus.proto.internal.StateCode", StateCode_name, StateCode_value)
	proto.RegisterEnum("milvus.proto.internal.InsertDataVersion", InsertDataVersion_name, InsertDataVersion_value)
	proto.RegisterType((*ComponentInfo)(nil), "milvus.proto.internal.ComponentInfo")
	proto.RegisterType((*ComponentStates)(nil), "milvus.proto.internal.ComponentStates")
	proto.RegisterType((*GetComponentStatesRequest)(nil), "milvus.proto.internal.GetComponentStatesRequest")
	proto.RegisterType((*GetTimeTickChannelRequest)(nil), "milvus.proto.internal.GetTimeTickChannelRequest")
	proto.RegisterType((*GetStatisticsChannelRequest)(nil), "milvus.proto.internal.GetStatisticsChannelRequest")
	proto.RegisterType((*GetDdChannelRequest)(nil), "milvus.proto.internal.GetDdChannelRequest")
	proto.RegisterType((*NodeInfo)(nil), "milvus.proto.internal.NodeInfo")
	proto.RegisterType((*InitParams)(nil), "milvus.proto.internal.InitParams")
	proto.RegisterType((*StringList)(nil), "milvus.proto.internal.StringList")
	proto.RegisterType((*TimeTickMsg)(nil), "milvus.proto.internal.TimeTickMsg")
	proto.RegisterType((*CreateCollectionRequest)(nil), "milvus.proto.internal.CreateCollectionRequest")
	proto.RegisterType((*DropCollectionRequest)(nil), "milvus.proto.internal.DropCollectionRequest")
	proto.RegisterType((*CreatePartitionRequest)(nil), "milvus.proto.internal.CreatePartitionRequest")
	proto.RegisterType((*DropPartitionRequest)(nil), "milvus.proto.internal.DropPartitionRequest")
	proto.RegisterType((*CreateAliasRequest)(nil), "milvus.proto.internal.CreateAliasRequest")
	proto.RegisterType((*DropAliasRequest)(nil), "milvus.proto.internal.DropAliasRequest")
	proto.RegisterType((*AlterAliasRequest)(nil), "milvus.proto.internal.AlterAliasRequest")
	proto.RegisterType((*CreateIndexRequest)(nil), "milvus.proto.internal.CreateIndexRequest")
	proto.RegisterType((*InsertRequest)(nil), "milvus.proto.internal.InsertRequest")
	proto.RegisterType((*SearchRequest)(nil), "milvus.proto.internal.SearchRequest")
	proto.RegisterType((*SearchResults)(nil), "milvus.proto.internal.SearchResults")
	proto.RegisterType((*RetrieveRequest)(nil), "milvus.proto.internal.RetrieveRequest")
	proto.RegisterType((*RetrieveResults)(nil), "milvus.proto.internal.RetrieveResults")
	proto.RegisterType((*DeleteRequest)(nil), "milvus.proto.internal.DeleteRequest")
	proto.RegisterType((*LoadIndex)(nil), "milvus.proto.internal.LoadIndex")
	proto.RegisterType((*IndexStats)(nil), "milvus.proto.internal.IndexStats")
	proto.RegisterType((*FieldStats)(nil), "milvus.proto.internal.FieldStats")
	proto.RegisterType((*SegmentStats)(nil), "milvus.proto.internal.SegmentStats")
	proto.RegisterType((*QueryNodeStats)(nil), "milvus.proto.internal.QueryNodeStats")
	proto.RegisterType((*MsgPosition)(nil), "milvus.proto.internal.MsgPosition")
	proto.RegisterType((*ChannelTimeTickMsg)(nil), "milvus.proto.internal.ChannelTimeTickMsg")
	proto.RegisterType((*ClearCredUsersCacheRequest)(nil), "milvus.proto.internal.ClearCredUsersCacheRequest")
	proto.RegisterType((*CredentialInfo)(nil), "milvus.proto.internal.CredentialInfo")
}

func init() { proto.RegisterFile("internal.proto", fileDescriptor_41f4a519b878ee3b) }

var fileDescriptor_41f4a519b878ee3b = []byte{
	// 2043 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x59, 0xcf, 0x73, 0x1c, 0x47,
	0x15, 0xce, 0xec, 0xac, 0xb4, 0xbb, 0x6f, 0x57, 0xab, 0x55, 0x4b, 0x76, 0xc6, 0xb2, 0x13, 0x2b,
	0x93, 0x00, 0xc2, 0x26, 0xb6, 0x51, 0x42, 0x92, 0x02, 0x0a, 0xc7, 0xda, 0x05, 0xb3, 0xe5, 0xd8,
	0x88, 0x91, 0xe3, 0x2a, 0xe0, 0x30, 0xd5, 0xbb, 0xd3, 0xda, 0x1d, 0x3c, 0x33, 0x3d, 0xe9, 0xee,
	0x91, 0xbc, 0x3e, 0x71, 0xe0, 0x04, 0x05, 0x55, 0x1c, 0x38, 0xc2, 0x8d, 0x33, 0x47, 0x4e, 0x40,
	0x15, 0xa7, 0x9c, 0xb8, 0xf3, 0xaf, 0x70, 0xa2, 0xfa, 0xc7, 0xcc, 0xce, 0xae, 0x56, 0xb2, 0xa4,
	0x54, 0x88, 0x53, 0x95, 0xdb, 0xf4, 0x7b, 0xaf, 0xbb, 0x5f, 0x7f, 0xef, 0x7b, 0xaf, 0x5f, 0xef,
	0x42, 0x3b, 0x4c, 0x04, 0x61, 0x09, 0x8e, 0x6e, 0xa5, 0x8c, 0x0a, 0x8a, 0x2e, 0xc5, 0x61, 0x74,
	0x98, 0x71, 0x3d, 0xba, 0x95, 0x2b, 0x37, 0x5b, 0x43, 0x1a, 0xc7, 0x34, 0xd1, 0xe2, 0xcd, 0x16,
	0x1f, 0x8e, 0x49, 0x8c, 0xf5, 0xc8, 0xfd, 0x87, 0x05, 0x2b, 0x5d, 0x1a, 0xa7, 0x34, 0x21, 0x89,
	0xe8, 0x27, 0x07, 0x14, 0x5d, 0x86, 0xe5, 0x84, 0x06, 0xa4, 0xdf, 0x73, 0xac, 0x2d, 0x6b, 0xdb,
	0xf6, 0xcc, 0x08, 0x21, 0xa8, 0x32, 0x1a, 0x11, 0xa7, 0xb2, 0x65, 0x6d, 0x37, 0x3c, 0xf5, 0x8d,
	0xee, 0x02, 0x70, 0x81, 0x05, 0xf1, 0x87, 0x34, 0x20, 0x8e, 0xbd, 0x65, 0x6d, 0xb7, 0x77, 0xb6,
	0x6e, 0x2d, 0xf4, 0xe2, 0xd6, 0xbe, 0x34, 0xec, 0xd2, 0x80, 0x78, 0x0d, 0x9e, 0x7f, 0xa2, 0x0f,
	0x01, 0xc8, 0x33, 0xc1, 0xb0, 0x1f, 0x26, 0x07, 0xd4, 0xa9, 0x6e, 0xd9, 0xdb, 0xcd, 0x9d, 0x37,
	0x66, 0x17, 0x30, 0xce, 0x3f, 0x20, 0x93, 0x27, 0x38, 0xca, 0xc8, 0x1e, 0x0e, 0x99, 0xd7, 0x50,
	0x93, 0xa4, 0xbb, 0xee, 0x7f, 0x2c, 0x58, 0x2d, 0x0e, 0xa0, 0xf6, 0xe0, 0xe8, 0xbb, 0xb0, 0xa4,
	0xb6, 0x50, 0x27, 0x68, 0xee, 0xbc, 0x75, 0x82, 0x47, 0x33, 0xe7, 0xf6, 0xf4, 0x14, 0xf4, 0x31,
	0xac, 0xf3, 0x6c, 0x30, 0xcc, 0x55, 0xbe, 0x92, 0x72, 0xa7, 0xa2, 0x5c, 0x3b, 0xdb, 0x4a, 0xa8,
	0xbc, 0x80, 0x71, 0xe9, 0x1d, 0x58, 0x96, 0x2b, 0x65, 0x5c, 0xa1, 0xd4, 0xdc, 0xb9, 0xba, 0xf0,
	0x90, 0xfb, 0xca, 0xc4, 0x33, 0xa6, 0xee, 0x55, 0xb8, 0x72, 0x9f, 0x88, 0xb9, 0xd3, 0x79, 0xe4,
	0x93, 0x8c, 0x70, 0x61, 0x94, 0x8f, 0xc3, 0x98, 0x3c, 0x0e, 0x87, 0x4f, 0xbb, 0x63, 0x9c, 0x24,
	0x24, 0xca, 0x95, 0xaf, 0xc1, 0xd5, 0xfb, 0x44, 0x4d, 0x08, 0xb9, 0x08, 0x87, 0x7c, 0x4e, 0x7d,
	0x09, 0xd6, 0xef, 0x13, 0xd1, 0x0b, 0xe6, 0xc4, 0x4f, 0xa0, 0xfe, 0x48, 0x06, 0x5b, 0xd2, 0xe0,
	0x3d, 0xa8, 0xe1, 0x20, 0x60, 0x84, 0x73, 0x83, 0xe2, 0xb5, 0x85, 0x1e, 0xdf, 0xd3, 0x36, 0x5e,
	0x6e, 0xbc, 0x88, 0x26, 0xee, 0x2f, 0x01, 0xfa, 0x49, 0x28, 0xf6, 0x30, 0xc3, 0x31, 0x3f, 0x91,
	0x60, 0x3d, 0x68, 0x71, 0x81, 0x99, 0xf0, 0x53, 0x65, 0x67, 0x20, 0x3f, 0x03, 0x1b, 0x9a, 0x6a,
	0x9a, 0x5e, 0xdd, 0xfd, 0x19, 0xc0, 0xbe, 0x60, 0x61, 0x32, 0xfa, 0x28, 0xe4, 0x42, 0xee, 0x75,
	0x28, 0xed, 0xe4, 0x21, 0xec, 0xed, 0x86, 0x67, 0x46, 0xa5, 0x70, 0x54, 0xce, 0x1e, 0x8e, 0xbb,
	0xd0, 0xcc, 0xe1, 0x7e, 0xc8, 0x47, 0xe8, 0x0e, 0x54, 0x07, 0x98, 0x93, 0x53, 0xe1, 0x79, 0xc8,
	0x47, 0xbb, 0x98, 0x13, 0x4f, 0x59, 0xba, 0xbf, 0xb1, 0xe1, 0xd5, 0x2e, 0x23, 0x8a, 0xfc, 0x51,
	0x44, 0x86, 0x22, 0xa4, 0x89, 0xc1, 0xfe, 0xfc, 0xab, 0xa1, 0x57, 0xa1, 0x16, 0x0c, 0xfc, 0x04,
	0xc7, 0x39, 0xd8, 0xcb, 0xc1, 0xe0, 0x11, 0x8e, 0x09, 0xfa, 0x3a, 0xb4, 0x87, 0xc5, 0xfa, 0x52,
	0xa2, 0x38, 0xd7, 0xf0, 0xe6, 0xa4, 0xe8, 0x2d, 0x58, 0x49, 0x31, 0x13, 0x61, 0x61, 0x56, 0x55,
	0x66, 0xb3, 0x42, 0x19, 0xd0, 0x60, 0xd0, 0xef, 0x39, 0x4b, 0x2a, 0x58, 0xea, 0x1b, 0xb9, 0xd0,
	0x9a, 0xae, 0xd5, 0xef, 0x39, 0xcb, 0x4a, 0x37, 0x23, 0x43, 0x5b, 0xd0, 0x2c, 0x16, 0xea, 0xf7,
	0x9c, 0x9a, 0x32, 0x29, 0x8b, 0x64, 0x70, 0x74, 0x2d, 0x72, 0xea, 0x5b, 0xd6, 0x76, 0xcb, 0x33,
	0x23, 0x74, 0x07, 0xd6, 0x0f, 0x43, 0x26, 0x32, 0x1c, 0x19, 0x7e, 0x4a, 0x3f, 0xb8, 0xd3, 0x50,
	0x11, 0x5c, 0xa4, 0x42, 0x3b, 0xb0, 0x91, 0x8e, 0x27, 0x3c, 0x1c, 0xce, 0x4d, 0x01, 0x35, 0x65,
	0xa1, 0xce, 0xfd, 0x97, 0x05, 0x97, 0x7a, 0x8c, 0xa6, 0x2f, 0x45, 0x28, 0x72, 0x90, 0xab, 0xa7,
	0x80, 0xbc, 0x74, 0x1c, 0x64, 0xf7, 0x77, 0x15, 0xb8, 0xac, 0x19, 0xb5, 0x97, 0x03, 0xfb, 0x39,
	0x9c, 0xe2, 0x1b, 0xb0, 0x3a, 0xdd, 0x55, 0x1b, 0x2c, 0x3e, 0xc6, 0xd7, 0xa0, 0x5d, 0x04, 0x58,
	0xdb, 0xfd, 0x7f, 0x29, 0xe5, 0xfe, 0xb6, 0x02, 0x1b, 0x32, 0xa8, 0x5f, 0xa1, 0x21, 0xd1, 0xf8,
	0xb3, 0x05, 0x48, 0xb3, 0xe3, 0x5e, 0x14, 0x62, 0xfe, 0x45, 0x62, 0xb1, 0x01, 0x4b, 0x58, 0xfa,
	0x60, 0x20, 0xd0, 0x03, 0x97, 0x43, 0x47, 0x46, 0xeb, 0xf3, 0xf2, 0xae, 0xd8, 0xd4, 0x2e, 0x6f,
	0xfa, 0x27, 0x0b, 0xd6, 0xee, 0x45, 0x82, 0xb0, 0x97, 0x14, 0x94, 0x7f, 0x56, 0xf2, 0xa8, 0xf5,
	0x93, 0x80, 0x3c, 0xfb, 0x22, 0x1d, 0x7c, 0x0d, 0xe0, 0x20, 0x24, 0x51, 0x50, 0x66, 0x6f, 0x43,
	0x49, 0x3e, 0x13, 0x73, 0x1d, 0xa8, 0xa9, 0x45, 0x0a, 0xd6, 0xe6, 0x43, 0xd9, 0x03, 0xe8, 0x7e,
	0xd0, 0xf4, 0x00, 0xf5, 0x33, 0xf7, 0x00, 0x6a, 0x9a, 0xe9, 0x01, 0xfe, 0x5d, 0x85, 0x95, 0x7e,
	0xc2, 0x09, 0x13, 0x17, 0x07, 0xef, 0x1a, 0x34, 0xf8, 0x18, 0x33, 0x75, 0x50, 0x03, 0xdf, 0x54,
	0x50, 0x86, 0xd6, 0x7e, 0x11, 0xb4, 0xd5, 0x33, 0x16, 0x87, 0xa5, 0xd3, 0x8a, 0xc3, 0xf2, 0x29,
	0x10, 0xd7, 0x5e, 0x5c, 0x1c, 0xea, 0xc7, 0x6f, 0x5f, 0x79, 0x40, 0x32, 0x8a, 0x65, 0xd3, 0xda,
	0x73, 0x1a, 0x4a, 0x3f, 0x15, 0xa0, 0xd7, 0x01, 0x44, 0x18, 0x13, 0x2e, 0x70, 0x9c, 0xea, 0x7b,
	0xb4, 0xea, 0x95, 0x24, 0xf2, 0xee, 0x66, 0xf4, 0xa8, 0xdf, 0xe3, 0x4e, 0x73, 0xcb, 0x96, 0x4d,
	0x9c, 0x1e, 0xa1, 0x77, 0xa1, 0xce, 0xe8, 0x91, 0x1f, 0x60, 0x81, 0x9d, 0x96, 0x0a, 0xde, 0x95,
	0x85, 0x60, 0xef, 0x46, 0x74, 0xe0, 0xd5, 0x18, 0x3d, 0xea, 0x61, 0x81, 0xd1, 0x5d, 0x68, 0x2a,
	0x06, 0x70, 0x3d, 0x71, 0x45, 0x4d, 0x7c, 0x7d, 0x76, 0xa2, 0x79, 0xb6, 0xfc, 0x48, 0xda, 0xc9,
	0x49, 0x9e, 0xa6, 0x26, 0x57, 0x0b, 0x5c, 0x81, 0x7a, 0x92, 0xc5, 0x3e, 0xa3, 0x47, 0xdc, 0x69,
	0x6f, 0x59, 0xdb, 0x55, 0xaf, 0x96, 0x64, 0xb1, 0x47, 0x8f, 0x38, 0xda, 0x85, 0xda, 0x21, 0x61,
	0x3c, 0xa4, 0x89, 0xb3, 0xaa, 0x1e, 0x28, 0xdb, 0x27, 0x34, 0xf1, 0x9a, 0x31, 0x72, 0xb9, 0x27,
	0xda, 0xde, 0xcb, 0x27, 0xba, 0x7f, 0xa9, 0xc2, 0xca, 0x3e, 0xc1, 0x6c, 0x38, 0xbe, 0x38, 0xa1,
	0xbe, 0x09, 0x1d, 0x46, 0x78, 0x16, 0x09, 0x7f, 0xa8, 0xdb, 0x90, 0x7e, 0xcf, 0xf0, 0x6a, 0x55,
	0xcb, 0xbb, 0xb9, 0xb8, 0x08, 0xba, 0x7d, 0x4a, 0xd0, 0xab, 0x0b, 0x82, 0xee, 0x42, 0xab, 0x14,
	0x61, 0xee, 0x2c, 0xa9, 0xd0, 0xcc, 0xc8, 0x50, 0x07, 0xec, 0x80, 0x47, 0x8a, 0x4f, 0x0d, 0x4f,
	0x7e, 0xa2, 0x9b, 0xb0, 0x96, 0x46, 0x78, 0x48, 0xc6, 0x34, 0x0a, 0x08, 0xf3, 0x47, 0x8c, 0x66,
	0xa9, 0xe2, 0x54, 0xcb, 0xeb, 0x94, 0x14, 0xf7, 0xa5, 0x1c, 0xbd, 0x0f, 0xf5, 0x80, 0x47, 0xbe,
	0x98, 0xa4, 0x44, 0x91, 0xaa, 0x7d, 0xc2, 0xd9, 0x7b, 0x3c, 0x7a, 0x3c, 0x49, 0x89, 0x57, 0x0b,
	0xf4, 0x07, 0xba, 0x03, 0x1b, 0x9c, 0xb0, 0x10, 0x47, 0xe1, 0x73, 0x12, 0xf8, 0xe4, 0x59, 0xca,
	0xfc, 0x34, 0xc2, 0x89, 0x62, 0x5e, 0xcb, 0x43, 0x53, 0xdd, 0x0f, 0x9f, 0xa5, 0x6c, 0x2f, 0xc2,
	0x09, 0xda, 0x86, 0x0e, 0xcd, 0x44, 0x9a, 0x09, 0xdf, 0x70, 0x23, 0x0c, 0x14, 0x11, 0x6d, 0xaf,
	0xad, 0xe5, 0x8a, 0x0a, 0xbc, 0x1f, 0x48, 0x68, 0x05, 0xc3, 0x87, 0x24, 0xf2, 0x0b, 0x86, 0x3a,
	0x4d, 0xc5, 0x82, 0x55, 0x2d, 0x7f, 0x9c, 0x8b, 0xd1, 0x6d, 0x58, 0x1f, 0x65, 0x98, 0xe1, 0x44,
	0x10, 0x52, 0xb2, 0x6e, 0x29, 0x6b, 0x54, 0xa8, 0xa6, 0x13, 0x6e, 0xc2, 0x9a, 0x34, 0xa3, 0x99,
	0x28, 0x99, 0xaf, 0x28, 0xf3, 0x8e, 0x51, 0x14, 0xc6, 0xee, 0x1f, 0x4a, 0x3c, 0x91, 0x21, 0xe5,
	0x17, 0xe0, 0xc9, 0x45, 0x9e, 0x26, 0x0b, 0xc9, 0x65, 0x2f, 0x26, 0xd7, 0x75, 0x68, 0xc6, 0x44,
	0xb0, 0x70, 0xa8, 0x83, 0xa8, 0xab, 0x13, 0x68, 0x91, 0x8a, 0xd4, 0x75, 0x68, 0xca, 0x5c, 0xfa,
	0x24, 0x23, 0x2c, 0x24, 0xdc, 0x14, 0x77, 0x48, 0xb2, 0xf8, 0xa7, 0x5a, 0x82, 0xd6, 0x61, 0x49,
	0xd0, 0xd4, 0x7f, 0x9a, 0x17, 0x25, 0x41, 0xd3, 0x07, 0xe8, 0xfb, 0xb0, 0xc9, 0x09, 0x8e, 0x48,
	0xe0, 0x17, 0x45, 0x84, 0xfb, 0x5c, 0x61, 0x41, 0x02, 0xa7, 0xa6, 0xe2, 0xe6, 0x68, 0x8b, 0xfd,
	0xc2, 0x60, 0xdf, 0xe8, 0x65, 0x58, 0x0a, 0xc7, 0x4b, 0xd3, 0xea, 0xaa, 0x7f, 0x47, 0x53, 0x55,
	0x31, 0xe1, 0x03, 0x70, 0x46, 0x11, 0x1d, 0xe0, 0xc8, 0x3f, 0xb6, 0xab, 0x7a, 0x28, 0xd8, 0xde,
	0x65, 0xad, 0xdf, 0x9f, 0xdb, 0x52, 0x1e, 0x8f, 0x47, 0xe1, 0x90, 0x04, 0xfe, 0x20, 0xa2, 0x03,
	0x07, 0x14, 0xff, 0x40, 0x8b, 0x64, 0x55, 0x92, 0xbc, 0x33, 0x06, 0x12, 0x86, 0x21, 0xcd, 0x12,
	0xa1, 0xd8, 0x64, 0x7b, 0x6d, 0x2d, 0x7f, 0x94, 0xc5, 0x5d, 0x29, 0x45, 0x6f, 0xc2, 0x8a, 0xb1,
	0xa4, 0x07, 0x07, 0x9c, 0x08, 0x45, 0x23, 0xdb, 0x6b, 0x69, 0xe1, 0x4f, 0x94, 0xcc, 0xfd, 0xab,
	0x0d, 0xab, 0x9e, 0x44, 0x97, 0x1c, 0x92, 0x2f, 0x7d, 0xf5, 0x38, 0x29, 0x8b, 0x97, 0xcf, 0x95,
	0xc5, 0xb5, 0x33, 0x67, 0x71, 0xfd, 0x5c, 0x59, 0xdc, 0x38, 0x5f, 0x16, 0xc3, 0x09, 0x59, 0xfc,
	0xf7, 0x99, 0x88, 0xbd, 0xac, 0x79, 0x7c, 0x03, 0xec, 0x30, 0xd0, 0xad, 0x63, 0x73, 0xc7, 0x59,
	0x78, 0x57, 0xf6, 0x7b, 0xdc, 0x93, 0x46, 0xf3, 0xf7, 0xeb, 0xd2, 0xb9, 0xef, 0xd7, 0x1f, 0xc0,
	0xd5, 0xe3, 0xd9, 0xcd, 0x0c, 0x46, 0x81, 0xb3, 0xac, 0x02, 0x7a, 0x65, 0x3e, 0xbd, 0x73, 0x10,
	0x03, 0xf4, 0x6d, 0xd8, 0x28, 0xe5, 0xf7, 0x74, 0x62, 0x4d, 0xbf, 0xe9, 0xa7, 0xba, 0xe9, 0x94,
	0xd3, 0x32, 0xbc, 0x7e, 0x5a, 0x86, 0xbb, 0x9f, 0xda, 0xb0, 0xd2, 0x23, 0x11, 0x11, 0xe4, 0xab,
	0xf6, 0xef, 0xc4, 0xf6, 0xef, 0x5b, 0x80, 0xc2, 0x44, 0xbc, 0xf7, 0xae, 0x9f, 0xb2, 0x30, 0xc6,
	0x6c, 0xe2, 0x3f, 0x25, 0x93, 0xbc, 0x74, 0x76, 0x94, 0x66, 0x4f, 0x2b, 0x1e, 0x90, 0x09, 0x7f,
	0x61, 0x3b, 0x58, 0xee, 0xbf, 0x74, 0xad, 0x2c, 0xfa, 0xaf, 0xef, 0x41, 0x6b, 0x66, 0x8b, 0xd6,
	0x0b, 0x08, 0xdb, 0x4c, 0xa7, 0xfb, 0xba, 0xff, 0xb5, 0xa0, 0xf1, 0x11, 0xc5, 0x81, 0x7a, 0x09,
	0x5d, 0x30, 0x8c, 0x45, 0x93, 0x5b, 0x99, 0x6f, 0x72, 0xaf, 0xc1, 0xf4, 0x31, 0x63, 0x02, 0x59,
	0x7a, 0xdd, 0x94, 0x5e, 0x29, 0xd5, 0xd9, 0x57, 0xca, 0x75, 0x68, 0x86, 0xd2, 0x21, 0x3f, 0xc5,
	0x62, 0xac, 0x0b, 0x65, 0xc3, 0x03, 0x25, 0xda, 0x93, 0x12, 0xf9, 0x8c, 0xc9, 0x0d, 0xd4, 0x33,
	0x66, 0xf9, 0xcc, 0xcf, 0x18, 0xb3, 0x88, 0x7a, 0xc6, 0xfc, 0xda, 0x02, 0x50, 0x07, 0x97, 0x45,
	0xe2, 0xf8, 0xa2, 0xd6, 0x45, 0x16, 0x95, 0x15, 0x5c, 0x45, 0x8a, 0x44, 0x58, 0x4c, 0x93, 0x8a,
	0x1b, 0x70, 0x90, 0x8c, 0x9a, 0x56, 0x99, 0x84, 0xe2, 0xee, 0xef, 0x2d, 0x00, 0x55, 0x15, 0xb4,
	0x1b, 0xf3, 0xf4, 0xb3, 0x4e, 0x7f, 0xe0, 0x55, 0x66, 0xa1, 0xdb, 0xcd, 0xa1, 0x93, 0x05, 0x4f,
	0x3e, 0xcc, 0x17, 0x9c, 0xa1, 0xd4, 0x91, 0xe7, 0x87, 0x37, 0xe8, 0xaa, 0x6f, 0xf7, 0x8f, 0x16,
	0xb4, 0x8c, 0x77, 0xda, 0xa5, 0x99, 0x28, 0x5b, 0xf3, 0x51, 0x56, 0x0d, 0x4f, 0x4c, 0xd9, 0xc4,
	0xe7, 0xe1, 0x73, 0x62, 0x1c, 0x02, 0x2d, 0xda, 0x0f, 0x9f, 0x93, 0x19, 0xf2, 0xda, 0xb3, 0xe4,
	0xbd, 0x09, 0x6b, 0x8c, 0x0c, 0x49, 0x22, 0xa2, 0x89, 0x1f, 0xd3, 0x20, 0x3c, 0x08, 0x49, 0xa0,
	0xd8, 0x50, 0xf7, 0x3a, 0xb9, 0xe2, 0xa1, 0x91, 0xbb, 0x9f, 0x5a, 0xd0, 0x96, 0x3d, 0xd2, 0xe4,
	0x11, 0x0d, 0x88, 0xf6, 0xec, 0xfc, 0x8c, 0xfd, 0x50, 0x9d, 0xc5, 0xc0, 0xa3, 0x7f, 0x02, 0x7f,
	0xf3, 0xa4, 0x7f, 0x54, 0x4a, 0x18, 0x78, 0x75, 0x4e, 0x46, 0x7a, 0xcf, 0x5d, 0x53, 0xec, 0xcf,
	0x04, 0xf1, 0x34, 0xb0, 0xa6, 0xde, 0x6b, 0x88, 0x7f, 0x65, 0x41, 0xf3, 0x21, 0x1f, 0xed, 0x51,
	0xae, 0xea, 0x05, 0x7a, 0x03, 0x5a, 0xa6, 0x46, 0xeb, 0x62, 0x65, 0xa9, 0x64, 0x69, 0x0e, 0xa7,
	0x3f, 0xa8, 0xa2, 0x0d, 0x58, 0x8a, 0xf9, 0xc8, 0x44, 0xbc, 0xe5, 0xe9, 0x01, 0xda, 0x84, 0x7a,
	0xcc, 0x47, 0xea, 0xed, 0x60, 0x32, 0xac, 0x18, 0xcb, 0xb0, 0x4d, 0x2f, 0xe3, 0xaa, 0xba, 0x8c,
	0xa7, 0x02, 0xf7, 0x6f, 0x16, 0x20, 0x73, 0xdb, 0x7d, 0xa6, 0x5f, 0xdd, 0x15, 0x61, 0xcb, 0x3f,
	0x0a, 0x57, 0x54, 0xba, 0xce, 0xc8, 0xe6, 0xea, 0x9b, 0x7d, 0xac, 0xbe, 0xdd, 0x84, 0xb5, 0x80,
	0x1c, 0x60, 0x79, 0x31, 0xcf, 0xbb, 0xdc, 0x31, 0x8a, 0x69, 0xff, 0x70, 0x0d, 0x36, 0xbb, 0x11,
	0xc1, 0xac, 0xcb, 0x48, 0xf0, 0x31, 0x27, 0x8c, 0x77, 0xf1, 0x70, 0x9c, 0xdf, 0x45, 0xee, 0x2f,
	0xa0, 0x2d, 0x15, 0x24, 0x11, 0x21, 0x8e, 0xd4, 0x5f, 0x2d, 0x9b, 0x50, 0xcf, 0xb8, 0x0c, 0x47,
	0x01, 0x6c, 0x31, 0x46, 0x6f, 0x03, 0x22, 0xc9, 0x90, 0x4d, 0x52, 0x99, 0xac, 0x29, 0xe6, 0xfc,
	0x88, 0xb2, 0xc0, 0x5c, 0x48, 0x6b, 0x85, 0x66, 0xcf, 0x28, 0x6e, 0x7c, 0x00, 0x8d, 0xe2, 0x7f,
	0x36, 0xd4, 0x81, 0x56, 0x3f, 0x09, 0x85, 0xea, 0xc8, 0xc2, 0x64, 0xd4, 0x79, 0x05, 0x35, 0xa1,
	0xf6, 0x63, 0x82, 0x23, 0x31, 0x9e, 0x74, 0x2c, 0xd4, 0x82, 0xfa, 0xbd, 0x41, 0x42, 0x59, 0x8c,
	0xa3, 0x4e, 0xe5, 0xc6, 0x0e, 0xac, 0x1d, 0x7b, 0x00, 0x4b, 0x13, 0x8f, 0x1e, 0x49, 0x2c, 0x83,
	0xce, 0x2b, 0x68, 0x15, 0x9a, 0x5d, 0x1a, 0x65, 0x71, 0xa2, 0x05, 0xd6, 0xee, 0xfb, 0x3f, 0xff,
	0xce, 0x28, 0x14, 0xe3, 0x6c, 0x20, 0x81, 0xbf, 0xad, 0x23, 0xf1, 0x76, 0x48, 0xcd, 0xd7, 0xed,
	0x9c, 0x64, 0xb7, 0x55, 0x70, 0x8a, 0x61, 0x3a, 0x18, 0x2c, 0x2b, 0xc9, 0x3b, 0xff, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0x48, 0x13, 0x23, 0xf5, 0xc1, 0x1c, 0x00, 0x00,
}
