# _*_ coding: utf-8 _*_

DEBUG = True
SQLALCHEMY_TRACK_MODIFICATIONS = False
# SECRET_KEY='A0Zr98j/3yX R~XHH!jmN]LWX/,?RT'
SQLALCHEMY_DATABASE_URI = "mysql+pymysql://vecwise@127.0.0.1:3306/vecdata"

ROW_LIMIT = 10000000
DATABASE_DIRECTORY = '/tmp'