package types

import (
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"

	"github.com/milvus-io/milvus/pkg/v3/proto/streamingpb"
	"github.com/milvus-io/milvus/pkg/v3/streaming/util/message"
)

// BroadcastAppendResult is the result of broadcast append operation.
type BroadcastAppendResult struct {
	BroadcastID   uint64                   // the broadcast id of the append operation.
	AppendResults map[string]*AppendResult // make the channel name to the append result.

	// Duplicated is non-nil when the broadcast was deduplicated by its idempotency
	// key: no new broadcast task was created, and BroadcastID is the ID of the
	// ORIGINAL broadcast. It carries the original broadcast message so the caller
	// can recover its own response payload (the import jobID, for imports).
	//
	// AppendResults is still filled in, rebuilt from the original broadcast's
	// persisted per-vchannel checkpoints, so a caller that only reads append
	// results cannot tell a deduplicated broadcast from a fresh one. The one
	// exception is an original that has not finished being acked, which leaves
	// AppendResults nil. The nil check is required, not defensive: the axis a key
	// is scoped on and the axis the caller's resource lock names are decoupled by
	// design — import scopes by collection ID so a retry still dedups across a
	// rename, but locks by collection name — so a same-scope retry can hold a
	// non-conflicting lock and observe an original that has not acked. On a
	// promoted secondary the same holds for a different reason: the dedup index
	// also carries tasks recovered from the WAL, which never held a lock at all.
	//
	// Only the in-process broadcaster path fills this field. The gRPC client path
	// (GRPCBroadcastServiceImpl.Broadcast) leaves it nil regardless of whether the
	// broadcast was deduplicated, so it must not be read as "was not a duplicate"
	// there.
	Duplicated message.BroadcastMutableMessage
}

// GetAppendResult returns the append result of the given channel.
//
// A deduplicated broadcast returns the ORIGINAL broadcast's result for the
// channel, so callers need no special handling for the duplicate path. It still
// returns nil when the original had not finished being acked; see Duplicated.
func (r *BroadcastAppendResult) GetAppendResult(channelName string) *AppendResult {
	return r.AppendResults[channelName]
}

// AppendResult is the result of append operation.
type AppendResult struct {
	// MessageID is generated by underlying walimpls.
	MessageID message.MessageID

	// LastConfirmedMessageID is the last confirmed message id.
	// From these message id, the reader can read all the messages which timetick is greater than the TimeTick in response.
	LastConfirmedMessageID message.MessageID

	// TimeTick is the time tick of the message.
	// Set by timetick interceptor.
	TimeTick uint64

	// TxnCtx is the transaction context of the message.
	// If the message is not belong to a transaction, the TxnCtx will be nil.
	TxnCtx *message.TxnContext

	// Extra is the extra information of the append result.
	Extra *anypb.Any
}

// GetExtra unmarshal the extra information to the given message.
func (r *AppendResult) GetExtra(m proto.Message) error {
	return anypb.UnmarshalTo(r.Extra, m, proto.UnmarshalOptions{
		DiscardUnknown: true,
		AllowPartial:   true,
	})
}

// IntoProto converts the append result to proto.
func (r *AppendResult) IntoProto() *streamingpb.ProduceMessageResponseResult {
	return &streamingpb.ProduceMessageResponseResult{
		Id:              r.MessageID.IntoProto(),
		Timetick:        r.TimeTick,
		TxnContext:      r.TxnCtx.IntoProto(),
		Extra:           r.Extra,
		LastConfirmedId: r.LastConfirmedMessageID.IntoProto(),
	}
}

// NewAppendResponseN creates a new append response.
func NewAppendResponseN(n int) AppendResponses {
	return AppendResponses{
		Responses: make([]AppendResponse, n),
	}
}

// AppendResponse is the response of one append operation.
type AppendResponse struct {
	AppendResult *AppendResult
	Error        error
}

// AppendResponses is the response of append operation.
type AppendResponses struct {
	Responses []AppendResponse
}

func (a AppendResponses) MaxTimeTick() uint64 {
	var maxTimeTick uint64
	for _, r := range a.Responses {
		if r.AppendResult != nil && r.AppendResult.TimeTick > maxTimeTick {
			maxTimeTick = r.AppendResult.TimeTick
		}
	}
	return maxTimeTick
}

// UnwrapFirstError returns the first error in the responses.
func (a AppendResponses) UnwrapFirstError() error {
	for _, r := range a.Responses {
		if r.Error != nil {
			return r.Error
		}
	}
	return nil
}

// FillAllError fills all the responses with the same error.
func (a *AppendResponses) FillAllError(err error) {
	for i := range a.Responses {
		a.Responses[i].Error = err
	}
}

// FillResponseAtIdx fill the response at idx
func (a *AppendResponses) FillResponseAtIdx(resp AppendResponse, idx int) {
	a.Responses[idx] = resp
}

func (a *AppendResponses) FillAllResponse(resp AppendResponse) {
	for i := range a.Responses {
		a.Responses[i] = resp
	}
}
