apiVersion: v1
kind: Pod
metadata:
  labels:
    app: milvus-e2e
  namespace: milvus-ci
spec:
  enableServiceLinks: false
  containers: 
  - name: pytest
    image: harbor.milvus.io/dockerhub/milvusdb/pytest:20230628-626516b
    resources:
      limits:
        cpu: "6"
        memory: 12Gi
      requests:
        cpu: "0.5"
        memory: 5Gi
    volumeMounts:
    - mountPath: /ci-logs
      name: ci-logs
  volumes:
  - name: ci-logs
    nfs:
      path: /ci-logs
      server: 172.16.70.239