apiVersion: v1
kind: Pod
metadata:
  labels:
    app: milvus-e2e
    task: milvus-e2e-pytest
  namespace: milvus-ci
spec:
  enableServiceLinks: false
  containers: 
  - name: pytest
    image: harbor.milvus.io/dockerhub/milvusdb/pytest:20231024-6e6de17
    resources:
      limits:
        cpu: "6"
        memory: 12Gi
      requests:
        cpu: "0.5"
        memory: 5Gi
    volumeMounts:
    - mountPath: /ci-logs
      name: ci-logs
  - name: main
    image: milvusdb/krte:20211213-dcc15e9
    env:
    - name: DOCKER_IN_DOCKER_ENABLED
      value: "true"
    - name: DOCKER_VOLUME_DIRECTORY
      value: "/mnt/disk/.docker"
    - name: DOCKER_CLIENT_TIMEOUT
      value: 240
    - name: COMPOSE_HTTP_TIMEOUT
      value: 240
    tty: true
    securityContext:
      privileged: true
    args: ["cat"]
    resources:
      limits:
        cpu: "6"
        memory: 12Gi
      requests:
        cpu: "0.5"
        memory: 2Gi
    volumeMounts:
    - mountPath: /docker-graph
      name: docker-graph
    - mountPath: /var/lib/docker
      name: docker-root
    - mountPath: /lib/modules
      name: modules
      readOnly: true
    - mountPath: /sys/fs/cgroup
      name: cgroup
    - mountPath: /mnt/disk/.docker
      name: build-cache
      subPath: docker-volume
    - mountPath: /ci-logs
      name: ci-logs  
  volumes:
  - emptyDir: {}
    name: docker-graph
  - emptyDir: {}
    name: docker-root
  - hostPath:
      path: /tmp/krte/cache
      type: DirectoryOrCreate
    name: build-cache
  - hostPath:
      path: /lib/modules
      type: Directory
    name: modules
  - hostPath:
      path: /sys/fs/cgroup
      type: Directory
    name: cgroup
  - name: ci-logs
    nfs:
      path: /volume1/ci-logs
      # path: /volume1/4am-logs
      server: 172.16.70.249