apiVersion: v1
kind: Pod
metadata:
  name: milvus-cpu-build-env
  labels:
    app: milvus
    componet: cpu-build-env
spec:
  containers:
  - name: milvus-cpu-build-env
    image: registry.zilliz.com/milvus/milvus-cpu-build-env:v0.10.1-ubuntu18.04
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: OS_NAME
      value: "ubuntu18.04"
    - name: BUILD_ENV_IMAGE_ID
      value: "78f93a8d512a5563ae29c2ba8aea4b1194d0ae7749b5973e20503ce9778d81e1"
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "14Gi"
        cpu: "6.0"
      requests:
        memory: "8Gi"
        cpu: "4.0"
    workingDir: /home/jenkins/agent
    env:
    - name: HOME
      value: /home/jenkins
  - name: milvus-mysql
    image: mysql:5.6
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: 123456
    ports:
    - containerPort: 3306
      name: mysql
    resources:
      limits:
        memory: "500Mi"
        cpu: "0.5"
      requests:
        memory: "200Mi"
        cpu: "0.2"
  tolerations:
  - key: dedicated
    operator: Equal
    value: milvus
    effect: NoSchedule
