quiet: False
with-expecter: True
inpackage: True
filename: "mock_{{.InterfaceNameSnake}}.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
dir: "{{.InterfaceDir}}"
packages:
  github.com/milvus-io/milvus/internal/datanode/allocator:
    interfaces:
      Allocator:
  github.com/milvus-io/milvus/internal/datanode/channel:
    interfaces:
      ChannelManager:
  github.com/milvus-io/milvus/internal/datanode/compaction:
    interfaces:
      Compactor:
