quiet: False
with-expecter: True
inpackage: True
filename: "mock_{{.InterfaceNameSnake}}.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
dir: "{{.InterfaceDir}}"
packages:
  github.com/milvus-io/milvus/internal/datanode/compactor:
    interfaces:
      Compactor:
  github.com/milvus-io/milvus/internal/datanode/importv2:
    interfaces:
      Task:
      TaskManager:
