// Licensed to the LF AI & Data foundation under one
// or more contributor license agreements. See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership. The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build ignore

// Command segcoregen regenerates segcore_codes_gen.go from milvus-common's
// enum ErrorCode (include/common/EasyAssert.h), which is the single source of
// truth for segcore error codes. It only emits the *list* of codes (and their
// names); the retry/ownership classification stays hand-maintained in
// classForCode. Keeping the list generated (instead of a hand-copied
// snapshot) makes the drift-guard test trustworthy: a code the C++ side adds
// that is not classified in the table now fails CI.
//
// The header path is provided explicitly so this tool has no build/conan
// coupling of its own; the `make generate-segcore-codes` target resolves the
// pinned milvus-common header (via `conan cache path`) and passes it here:
//
//	go run ./internal/segcoregen -header <EasyAssert.h> -out segcore_codes_gen.go
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// Only ErrorCode values in the segcore range are relevant to the Go classifier;
// Success (0) and any non-segcore entries are ignored.
const minSegcoreCode = 2000

var (
	enumStart = regexp.MustCompile(`enum\s+ErrorCode\s*\{`)
	// e.g. "    UnexpectedError = 2001,"  (tolerates trailing comment)
	entry = regexp.MustCompile(`^\s*([A-Za-z_]\w*)\s*=\s*(\d+)\s*,`)
)

func main() {
	header := flag.String("header", os.Getenv("MILVUS_COMMON_HEADER"), "path to milvus-common include/common/EasyAssert.h")
	out := flag.String("out", "segcore_codes_gen.go", "output Go file")
	flag.Parse()

	if *header == "" {
		fatalf("no header: pass -header <EasyAssert.h> or set MILVUS_COMMON_HEADER")
	}
	names, codes := parseEnum(*header)
	if len(codes) == 0 {
		// Fail loudly rather than emit an empty list (a silent empty list would
		// make the drift-guard vacuously pass).
		fatalf("parsed 0 ErrorCode values from %s -- enum format changed?", *header)
	}
	if err := os.WriteFile(*out, render(names, codes), 0o644); err != nil {
		fatalf("write %s: %v", *out, err)
	}
	fmt.Printf("segcoregen: wrote %d codes to %s from %s\n", len(codes), *out, *header)
}

// parseEnum extracts the { name -> value } pairs of `enum ErrorCode` with value
// >= minSegcoreCode, returning them ordered by value.
func parseEnum(path string) (map[int32]string, []int32) {
	f, err := os.Open(path)
	if err != nil {
		fatalf("open %s: %v", path, err)
	}
	defer f.Close()

	names := map[int32]string{}
	inEnum := false
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if !inEnum {
			if enumStart.MatchString(line) {
				inEnum = true
			}
			continue
		}
		if strings.Contains(line, "}") {
			break
		}
		m := entry.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		v, err := strconv.Atoi(m[2])
		if err != nil || int32(v) < minSegcoreCode {
			continue
		}
		names[int32(v)] = m[1]
	}
	if err := sc.Err(); err != nil {
		fatalf("read %s: %v", path, err)
	}
	if !inEnum {
		fatalf("no `enum ErrorCode {` found in %s", path)
	}

	codes := make([]int32, 0, len(names))
	for c := range names {
		codes = append(codes, c)
	}
	sort.Slice(codes, func(i, j int) bool { return codes[i] < codes[j] })
	return names, codes
}

func render(names map[int32]string, codes []int32) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by internal/segcoregen; DO NOT EDIT.\n")
	b.WriteString("// Source of truth: milvus-common include/common/EasyAssert.h (enum ErrorCode).\n")
	b.WriteString("// Regenerate with `make generate-segcore-codes`.\n\n")
	b.WriteString("package merr\n\n")

	b.WriteString("// SegcoreCode is a milvus::ErrorCode value produced by the C++ core and carried\n")
	b.WriteString("// over the cgo boundary. Its constants are the single source of truth for the\n")
	b.WriteString("// classification switch in segcore.go: that switch is marked\n")
	b.WriteString("// //exhaustive:enforce, so adding a constant here without a case there fails\n")
	b.WriteString("// the `exhaustive` linter (near-compile-time drift protection across the\n")
	b.WriteString("// C++->Go seam).\n")
	b.WriteString("type SegcoreCode int32\n\n")

	b.WriteString("const (\n")
	for _, c := range codes {
		fmt.Fprintf(&b, "\tCode%s SegcoreCode = %d\n", names[c], c)
	}
	b.WriteString(")\n\n")

	b.WriteString("// segcoreCodeNames maps each code to its C++ enum name, for diagnostics.\n")
	b.WriteString("var segcoreCodeNames = map[SegcoreCode]string{\n")
	for _, c := range codes {
		fmt.Fprintf(&b, "\tCode%s: %q,\n", names[c], names[c])
	}
	b.WriteString("}\n")
	return []byte(b.String())
}

func fatalf(format string, a ...any) {
	fmt.Fprintf(os.Stderr, "segcoregen: "+format+"\n", a...)
	os.Exit(1)
}
