quiet: False
with-expecter: True
filename: "mock_{{.InterfaceName}}.go"
dir: 'internal/mocks/{{trimPrefix .PackagePath "github.com/milvus-io/milvus/internal" | dir }}/mock_{{.PackageName}}'
mockname: "Mock{{.InterfaceName}}"
outpkg: "mock_{{.PackageName}}"
packages:
  github.com/milvus-io/milvus/internal/distributed/streaming:
    interfaces:
      WALAccesser:
      Utility:
      Broadcast:
  github.com/milvus-io/milvus/internal/streamingcoord/server/balancer:
    interfaces:
      Balancer:
  github.com/milvus-io/milvus/internal/streamingcoord/server/broadcaster:
    interfaces:
      AppendOperator:
      Watcher:
  github.com/milvus-io/milvus/internal/streamingcoord/client:
    interfaces:
      Client:
      BroadcastService:
  github.com/milvus-io/milvus/internal/streamingcoord/client/broadcast:
    interfaces:
      Watcher:
  github.com/milvus-io/milvus/internal/streamingnode/client/manager:
    interfaces:
      ManagerClient:
  github.com/milvus-io/milvus/internal/streamingnode/client/handler:
    interfaces:
      HandlerClient:
  github.com/milvus-io/milvus/internal/streamingnode/client/handler/assignment:
    interfaces:
      Watcher:
  github.com/milvus-io/milvus/internal/streamingnode/client/handler/producer:
    interfaces:
      Producer:
  github.com/milvus-io/milvus/internal/streamingnode/client/handler/consumer:
    interfaces:
      Consumer:
  github.com/milvus-io/milvus/internal/streamingnode/server/flusher:
    interfaces:
      Flusher:
      FlushMsgHandler:
  github.com/milvus-io/milvus/internal/streamingnode/server/wal:
    interfaces:
      OpenerBuilder:
      Opener:
      Scanner:
      WAL:
  github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors:
    interfaces:
      Interceptor:
      InterceptorWithReady:
      InterceptorBuilder:
  github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/segment/inspector:
    interfaces:
      SealOperator:
  github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/timetick/inspector:
    interfaces:
      TimeTickSyncOperator:
  google.golang.org/grpc:
    interfaces:
      ClientStream:
  github.com/milvus-io/milvus/internal/streamingnode/server/walmanager:
    interfaces:
      Manager:
  github.com/milvus-io/milvus/internal/metastore:
    interfaces:
      StreamingCoordCataLog:
      StreamingNodeCataLog:
  github.com/milvus-io/milvus/internal/util/segcore:
    interfaces:
      CSegment:
  github.com/milvus-io/milvus/internal/util/streamingutil/service/discoverer:
    interfaces:
      Discoverer:
      AssignmentDiscoverWatcher:
  github.com/milvus-io/milvus/internal/util/streamingutil/service/lazygrpc:
    interfaces:
      Service:
  github.com/milvus-io/milvus/internal/util/streamingutil/service/resolver:
    interfaces:
      Resolver:
      Builder:
  github.com/milvus-io/milvus/internal/util/searchutil/optimizers:
    interfaces:
      QueryHook:
#  github.com/milvus-io/milvus/internal/flushcommon/util:
#    interfaces:
#      MsgHandler:
  google.golang.org/grpc/resolver:
    interfaces:
      ClientConn:
  google.golang.org/grpc/balancer:
    interfaces:
      SubConn:
