- name: etcd volume
  docker_volume:
    name: etcd_volume

- name: etcd
  docker_container: 
    name: etcd
    image: quay.io/coreos/etcd:v3.5.18
    volumes:
      - etcd_volume:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    env:
      ETCD_AUTO_COMPACTION_MODE: revision
      ETCD_AUTO_COMPACTION_RETENTION: "1000"
      ETCD_QUOTA_BACKEND_BYTES: "4294967296"
    network_mode: "{{dependencies_network}}" #Use the network which defined as variable in Inventory.