// Licensed to the LF AI & Data foundation under one
// or more contributor license agreements. See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership. The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: pyudf.proto

package pyudfpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PyUDFWorker_Execute_FullMethodName = "/milvus.proto.pyudf.PyUDFWorker/Execute"
)

// PyUDFWorkerClient is the client API for PyUDFWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PyUDFWorkerClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type pyUDFWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewPyUDFWorkerClient(cc grpc.ClientConnInterface) PyUDFWorkerClient {
	return &pyUDFWorkerClient{cc}
}

func (c *pyUDFWorkerClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, PyUDFWorker_Execute_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PyUDFWorkerServer is the server API for PyUDFWorker service.
// All implementations should embed UnimplementedPyUDFWorkerServer
// for forward compatibility
type PyUDFWorkerServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
}

// UnimplementedPyUDFWorkerServer should be embedded to have forward compatible implementations.
type UnimplementedPyUDFWorkerServer struct {
}

func (UnimplementedPyUDFWorkerServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}

// UnsafePyUDFWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PyUDFWorkerServer will
// result in compilation errors.
type UnsafePyUDFWorkerServer interface {
	mustEmbedUnimplementedPyUDFWorkerServer()
}

func RegisterPyUDFWorkerServer(s grpc.ServiceRegistrar, srv PyUDFWorkerServer) {
	s.RegisterService(&PyUDFWorker_ServiceDesc, srv)
}

func _PyUDFWorker_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PyUDFWorkerServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PyUDFWorker_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PyUDFWorkerServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PyUDFWorker_ServiceDesc is the grpc.ServiceDesc for PyUDFWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PyUDFWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "milvus.proto.pyudf.PyUDFWorker",
	HandlerType: (*PyUDFWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _PyUDFWorker_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pyudf.proto",
}
